/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodayRouteImport } from './routes/today'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProgramRouteImport } from './routes/program'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccountDeletionRouteImport } from './routes/account-deletion'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesNewRouteImport } from './routes/templates.new'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions.$sessionId'
import { Route as HistoryMovementIdRouteImport } from './routes/history.$movementId'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as SessionsSessionIdIndexRouteImport } from './routes/sessions.$sessionId.index'
import { Route as TemplatesTemplateIdStartRouteImport } from './routes/templates.$templateId.start'
import { Route as SessionsSessionIdSummaryRouteImport } from './routes/sessions.$sessionId.summary'

const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramRoute = ProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/history.lazy').then((d) => d.Route))
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDeletionRoute = AccountDeletionRouteImport.update({
  id: '/account-deletion',
  path: '/account-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const TemplatesNewRoute = TemplatesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TemplatesRoute,
} as any).lazy(() => import('./routes/templates.new.lazy').then((d) => d.Route))
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryMovementIdRoute = HistoryMovementIdRouteImport.update({
  id: '/$movementId',
  path: '/$movementId',
  getParentRoute: () => HistoryRoute,
} as any).lazy(() =>
  import('./routes/history.$movementId.lazy').then((d) => d.Route),
)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const SessionsSessionIdIndexRoute = SessionsSessionIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SessionsSessionIdRoute,
} as any)
const TemplatesTemplateIdStartRoute =
  TemplatesTemplateIdStartRouteImport.update({
    id: '/$templateId/start',
    path: '/$templateId/start',
    getParentRoute: () => TemplatesRoute,
  } as any)
const SessionsSessionIdSummaryRoute =
  SessionsSessionIdSummaryRouteImport.update({
    id: '/summary',
    path: '/summary',
    getParentRoute: () => SessionsSessionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-deletion': typeof AccountDeletionRoute
  '/auth': typeof AuthRouteWithChildren
  '/history': typeof HistoryRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/program': typeof ProgramRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/terms': typeof TermsRoute
  '/today': typeof TodayRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/history/$movementId': typeof HistoryMovementIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRouteWithChildren
  '/templates/new': typeof TemplatesNewRoute
  '/sessions/$sessionId/summary': typeof SessionsSessionIdSummaryRoute
  '/templates/$templateId/start': typeof TemplatesTemplateIdStartRoute
  '/sessions/$sessionId/': typeof SessionsSessionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-deletion': typeof AccountDeletionRoute
  '/auth': typeof AuthRouteWithChildren
  '/history': typeof HistoryRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/program': typeof ProgramRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/terms': typeof TermsRoute
  '/today': typeof TodayRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/history/$movementId': typeof HistoryMovementIdRoute
  '/templates/new': typeof TemplatesNewRoute
  '/sessions/$sessionId/summary': typeof SessionsSessionIdSummaryRoute
  '/templates/$templateId/start': typeof TemplatesTemplateIdStartRoute
  '/sessions/$sessionId': typeof SessionsSessionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account-deletion': typeof AccountDeletionRoute
  '/auth': typeof AuthRouteWithChildren
  '/history': typeof HistoryRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/program': typeof ProgramRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/terms': typeof TermsRoute
  '/today': typeof TodayRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/history/$movementId': typeof HistoryMovementIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRouteWithChildren
  '/templates/new': typeof TemplatesNewRoute
  '/sessions/$sessionId/summary': typeof SessionsSessionIdSummaryRoute
  '/templates/$templateId/start': typeof TemplatesTemplateIdStartRoute
  '/sessions/$sessionId/': typeof SessionsSessionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-deletion'
    | '/auth'
    | '/history'
    | '/privacy'
    | '/program'
    | '/settings'
    | '/templates'
    | '/terms'
    | '/today'
    | '/auth/callback'
    | '/history/$movementId'
    | '/sessions/$sessionId'
    | '/templates/new'
    | '/sessions/$sessionId/summary'
    | '/templates/$templateId/start'
    | '/sessions/$sessionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-deletion'
    | '/auth'
    | '/history'
    | '/privacy'
    | '/program'
    | '/settings'
    | '/templates'
    | '/terms'
    | '/today'
    | '/auth/callback'
    | '/history/$movementId'
    | '/templates/new'
    | '/sessions/$sessionId/summary'
    | '/templates/$templateId/start'
    | '/sessions/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/account-deletion'
    | '/auth'
    | '/history'
    | '/privacy'
    | '/program'
    | '/settings'
    | '/templates'
    | '/terms'
    | '/today'
    | '/auth/callback'
    | '/history/$movementId'
    | '/sessions/$sessionId'
    | '/templates/new'
    | '/sessions/$sessionId/summary'
    | '/templates/$templateId/start'
    | '/sessions/$sessionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountDeletionRoute: typeof AccountDeletionRoute
  AuthRoute: typeof AuthRouteWithChildren
  HistoryRoute: typeof HistoryRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ProgramRoute: typeof ProgramRoute
  SettingsRoute: typeof SettingsRoute
  TemplatesRoute: typeof TemplatesRouteWithChildren
  TermsRoute: typeof TermsRoute
  TodayRoute: typeof TodayRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program': {
      id: '/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof ProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-deletion': {
      id: '/account-deletion'
      path: '/account-deletion'
      fullPath: '/account-deletion'
      preLoaderRoute: typeof AccountDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/new': {
      id: '/templates/new'
      path: '/new'
      fullPath: '/templates/new'
      preLoaderRoute: typeof TemplatesNewRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$movementId': {
      id: '/history/$movementId'
      path: '/$movementId'
      fullPath: '/history/$movementId'
      preLoaderRoute: typeof HistoryMovementIdRouteImport
      parentRoute: typeof HistoryRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/sessions/$sessionId/': {
      id: '/sessions/$sessionId/'
      path: '/'
      fullPath: '/sessions/$sessionId/'
      preLoaderRoute: typeof SessionsSessionIdIndexRouteImport
      parentRoute: typeof SessionsSessionIdRoute
    }
    '/templates/$templateId/start': {
      id: '/templates/$templateId/start'
      path: '/$templateId/start'
      fullPath: '/templates/$templateId/start'
      preLoaderRoute: typeof TemplatesTemplateIdStartRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/sessions/$sessionId/summary': {
      id: '/sessions/$sessionId/summary'
      path: '/summary'
      fullPath: '/sessions/$sessionId/summary'
      preLoaderRoute: typeof SessionsSessionIdSummaryRouteImport
      parentRoute: typeof SessionsSessionIdRoute
    }
  }
}

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface HistoryRouteChildren {
  HistoryMovementIdRoute: typeof HistoryMovementIdRoute
}

const HistoryRouteChildren: HistoryRouteChildren = {
  HistoryMovementIdRoute: HistoryMovementIdRoute,
}

const HistoryRouteWithChildren =
  HistoryRoute._addFileChildren(HistoryRouteChildren)

interface TemplatesRouteChildren {
  TemplatesNewRoute: typeof TemplatesNewRoute
  TemplatesTemplateIdStartRoute: typeof TemplatesTemplateIdStartRoute
}

const TemplatesRouteChildren: TemplatesRouteChildren = {
  TemplatesNewRoute: TemplatesNewRoute,
  TemplatesTemplateIdStartRoute: TemplatesTemplateIdStartRoute,
}

const TemplatesRouteWithChildren = TemplatesRoute._addFileChildren(
  TemplatesRouteChildren,
)

interface SessionsSessionIdRouteChildren {
  SessionsSessionIdSummaryRoute: typeof SessionsSessionIdSummaryRoute
  SessionsSessionIdIndexRoute: typeof SessionsSessionIdIndexRoute
}

const SessionsSessionIdRouteChildren: SessionsSessionIdRouteChildren = {
  SessionsSessionIdSummaryRoute: SessionsSessionIdSummaryRoute,
  SessionsSessionIdIndexRoute: SessionsSessionIdIndexRoute,
}

const SessionsSessionIdRouteWithChildren =
  SessionsSessionIdRoute._addFileChildren(SessionsSessionIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountDeletionRoute: AccountDeletionRoute,
  AuthRoute: AuthRouteWithChildren,
  HistoryRoute: HistoryRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ProgramRoute: ProgramRoute,
  SettingsRoute: SettingsRoute,
  TemplatesRoute: TemplatesRouteWithChildren,
  TermsRoute: TermsRoute,
  TodayRoute: TodayRoute,
  SessionsSessionIdRoute: SessionsSessionIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
