/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodayRouteImport } from './routes/today'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProgramRouteImport } from './routes/program'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions.$sessionId'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as SessionsSessionIdIndexRouteImport } from './routes/sessions.$sessionId.index'
import { Route as TemplatesTemplateIdStartRouteImport } from './routes/templates.$templateId.start'
import { Route as SessionsSessionIdSummaryRouteImport } from './routes/sessions.$sessionId.summary'
import { Route as ApiV1TodayRouteImport } from './routes/api.v1.today'
import { Route as ApiV1SessionsRouteImport } from './routes/api.v1.sessions'
import { Route as ApiV1MeRouteImport } from './routes/api.v1.me'
import { Route as ApiV1SessionsSessionIdRouteImport } from './routes/api.v1.sessions.$sessionId'
import { Route as ApiV1AuthMagicLinkIntentRouteImport } from './routes/api.v1.auth.magic-link-intent'
import { Route as ApiV1SessionsSessionIdSetsExerciseLogIdSetIndexRouteImport } from './routes/api.v1.sessions.$sessionId.sets.$exerciseLogId.$setIndex'

const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramRoute = ProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const SessionsSessionIdIndexRoute = SessionsSessionIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SessionsSessionIdRoute,
} as any)
const TemplatesTemplateIdStartRoute =
  TemplatesTemplateIdStartRouteImport.update({
    id: '/$templateId/start',
    path: '/$templateId/start',
    getParentRoute: () => TemplatesRoute,
  } as any)
const SessionsSessionIdSummaryRoute =
  SessionsSessionIdSummaryRouteImport.update({
    id: '/summary',
    path: '/summary',
    getParentRoute: () => SessionsSessionIdRoute,
  } as any)
const ApiV1TodayRoute = ApiV1TodayRouteImport.update({
  id: '/api/v1/today',
  path: '/api/v1/today',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SessionsRoute = ApiV1SessionsRouteImport.update({
  id: '/api/v1/sessions',
  path: '/api/v1/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MeRoute = ApiV1MeRouteImport.update({
  id: '/api/v1/me',
  path: '/api/v1/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SessionsSessionIdRoute = ApiV1SessionsSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => ApiV1SessionsRoute,
} as any)
const ApiV1AuthMagicLinkIntentRoute =
  ApiV1AuthMagicLinkIntentRouteImport.update({
    id: '/api/v1/auth/magic-link-intent',
    path: '/api/v1/auth/magic-link-intent',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1SessionsSessionIdSetsExerciseLogIdSetIndexRoute =
  ApiV1SessionsSessionIdSetsExerciseLogIdSetIndexRouteImport.update({
    id: '/sets/$exerciseLogId/$setIndex',
    path: '/sets/$exerciseLogId/$setIndex',
    getParentRoute: () => ApiV1SessionsSessionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/history': typeof HistoryRoute
  '/program': typeof ProgramRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/today': typeof TodayRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRouteWithChildren
  '/api/v1/me': typeof ApiV1MeRoute
  '/api/v1/sessions': typeof ApiV1SessionsRouteWithChildren
  '/api/v1/today': typeof ApiV1TodayRoute
  '/sessions/$sessionId/summary': typeof SessionsSessionIdSummaryRoute
  '/templates/$templateId/start': typeof TemplatesTemplateIdStartRoute
  '/sessions/$sessionId/': typeof SessionsSessionIdIndexRoute
  '/api/v1/auth/magic-link-intent': typeof ApiV1AuthMagicLinkIntentRoute
  '/api/v1/sessions/$sessionId': typeof ApiV1SessionsSessionIdRouteWithChildren
  '/api/v1/sessions/$sessionId/sets/$exerciseLogId/$setIndex': typeof ApiV1SessionsSessionIdSetsExerciseLogIdSetIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/history': typeof HistoryRoute
  '/program': typeof ProgramRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/today': typeof TodayRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/v1/me': typeof ApiV1MeRoute
  '/api/v1/sessions': typeof ApiV1SessionsRouteWithChildren
  '/api/v1/today': typeof ApiV1TodayRoute
  '/sessions/$sessionId/summary': typeof SessionsSessionIdSummaryRoute
  '/templates/$templateId/start': typeof TemplatesTemplateIdStartRoute
  '/sessions/$sessionId': typeof SessionsSessionIdIndexRoute
  '/api/v1/auth/magic-link-intent': typeof ApiV1AuthMagicLinkIntentRoute
  '/api/v1/sessions/$sessionId': typeof ApiV1SessionsSessionIdRouteWithChildren
  '/api/v1/sessions/$sessionId/sets/$exerciseLogId/$setIndex': typeof ApiV1SessionsSessionIdSetsExerciseLogIdSetIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/history': typeof HistoryRoute
  '/program': typeof ProgramRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/today': typeof TodayRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRouteWithChildren
  '/api/v1/me': typeof ApiV1MeRoute
  '/api/v1/sessions': typeof ApiV1SessionsRouteWithChildren
  '/api/v1/today': typeof ApiV1TodayRoute
  '/sessions/$sessionId/summary': typeof SessionsSessionIdSummaryRoute
  '/templates/$templateId/start': typeof TemplatesTemplateIdStartRoute
  '/sessions/$sessionId/': typeof SessionsSessionIdIndexRoute
  '/api/v1/auth/magic-link-intent': typeof ApiV1AuthMagicLinkIntentRoute
  '/api/v1/sessions/$sessionId': typeof ApiV1SessionsSessionIdRouteWithChildren
  '/api/v1/sessions/$sessionId/sets/$exerciseLogId/$setIndex': typeof ApiV1SessionsSessionIdSetsExerciseLogIdSetIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/history'
    | '/program'
    | '/settings'
    | '/templates'
    | '/today'
    | '/auth/callback'
    | '/sessions/$sessionId'
    | '/api/v1/me'
    | '/api/v1/sessions'
    | '/api/v1/today'
    | '/sessions/$sessionId/summary'
    | '/templates/$templateId/start'
    | '/sessions/$sessionId/'
    | '/api/v1/auth/magic-link-intent'
    | '/api/v1/sessions/$sessionId'
    | '/api/v1/sessions/$sessionId/sets/$exerciseLogId/$setIndex'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/history'
    | '/program'
    | '/settings'
    | '/templates'
    | '/today'
    | '/auth/callback'
    | '/api/v1/me'
    | '/api/v1/sessions'
    | '/api/v1/today'
    | '/sessions/$sessionId/summary'
    | '/templates/$templateId/start'
    | '/sessions/$sessionId'
    | '/api/v1/auth/magic-link-intent'
    | '/api/v1/sessions/$sessionId'
    | '/api/v1/sessions/$sessionId/sets/$exerciseLogId/$setIndex'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/history'
    | '/program'
    | '/settings'
    | '/templates'
    | '/today'
    | '/auth/callback'
    | '/sessions/$sessionId'
    | '/api/v1/me'
    | '/api/v1/sessions'
    | '/api/v1/today'
    | '/sessions/$sessionId/summary'
    | '/templates/$templateId/start'
    | '/sessions/$sessionId/'
    | '/api/v1/auth/magic-link-intent'
    | '/api/v1/sessions/$sessionId'
    | '/api/v1/sessions/$sessionId/sets/$exerciseLogId/$setIndex'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  HistoryRoute: typeof HistoryRoute
  ProgramRoute: typeof ProgramRoute
  SettingsRoute: typeof SettingsRoute
  TemplatesRoute: typeof TemplatesRouteWithChildren
  TodayRoute: typeof TodayRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRouteWithChildren
  ApiV1MeRoute: typeof ApiV1MeRoute
  ApiV1SessionsRoute: typeof ApiV1SessionsRouteWithChildren
  ApiV1TodayRoute: typeof ApiV1TodayRoute
  ApiV1AuthMagicLinkIntentRoute: typeof ApiV1AuthMagicLinkIntentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program': {
      id: '/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof ProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/sessions/$sessionId/': {
      id: '/sessions/$sessionId/'
      path: '/'
      fullPath: '/sessions/$sessionId/'
      preLoaderRoute: typeof SessionsSessionIdIndexRouteImport
      parentRoute: typeof SessionsSessionIdRoute
    }
    '/templates/$templateId/start': {
      id: '/templates/$templateId/start'
      path: '/$templateId/start'
      fullPath: '/templates/$templateId/start'
      preLoaderRoute: typeof TemplatesTemplateIdStartRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/sessions/$sessionId/summary': {
      id: '/sessions/$sessionId/summary'
      path: '/summary'
      fullPath: '/sessions/$sessionId/summary'
      preLoaderRoute: typeof SessionsSessionIdSummaryRouteImport
      parentRoute: typeof SessionsSessionIdRoute
    }
    '/api/v1/today': {
      id: '/api/v1/today'
      path: '/api/v1/today'
      fullPath: '/api/v1/today'
      preLoaderRoute: typeof ApiV1TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/sessions': {
      id: '/api/v1/sessions'
      path: '/api/v1/sessions'
      fullPath: '/api/v1/sessions'
      preLoaderRoute: typeof ApiV1SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/me': {
      id: '/api/v1/me'
      path: '/api/v1/me'
      fullPath: '/api/v1/me'
      preLoaderRoute: typeof ApiV1MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/sessions/$sessionId': {
      id: '/api/v1/sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/api/v1/sessions/$sessionId'
      preLoaderRoute: typeof ApiV1SessionsSessionIdRouteImport
      parentRoute: typeof ApiV1SessionsRoute
    }
    '/api/v1/auth/magic-link-intent': {
      id: '/api/v1/auth/magic-link-intent'
      path: '/api/v1/auth/magic-link-intent'
      fullPath: '/api/v1/auth/magic-link-intent'
      preLoaderRoute: typeof ApiV1AuthMagicLinkIntentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/sessions/$sessionId/sets/$exerciseLogId/$setIndex': {
      id: '/api/v1/sessions/$sessionId/sets/$exerciseLogId/$setIndex'
      path: '/sets/$exerciseLogId/$setIndex'
      fullPath: '/api/v1/sessions/$sessionId/sets/$exerciseLogId/$setIndex'
      preLoaderRoute: typeof ApiV1SessionsSessionIdSetsExerciseLogIdSetIndexRouteImport
      parentRoute: typeof ApiV1SessionsSessionIdRoute
    }
  }
}

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface TemplatesRouteChildren {
  TemplatesTemplateIdStartRoute: typeof TemplatesTemplateIdStartRoute
}

const TemplatesRouteChildren: TemplatesRouteChildren = {
  TemplatesTemplateIdStartRoute: TemplatesTemplateIdStartRoute,
}

const TemplatesRouteWithChildren = TemplatesRoute._addFileChildren(
  TemplatesRouteChildren,
)

interface SessionsSessionIdRouteChildren {
  SessionsSessionIdSummaryRoute: typeof SessionsSessionIdSummaryRoute
  SessionsSessionIdIndexRoute: typeof SessionsSessionIdIndexRoute
}

const SessionsSessionIdRouteChildren: SessionsSessionIdRouteChildren = {
  SessionsSessionIdSummaryRoute: SessionsSessionIdSummaryRoute,
  SessionsSessionIdIndexRoute: SessionsSessionIdIndexRoute,
}

const SessionsSessionIdRouteWithChildren =
  SessionsSessionIdRoute._addFileChildren(SessionsSessionIdRouteChildren)

interface ApiV1SessionsSessionIdRouteChildren {
  ApiV1SessionsSessionIdSetsExerciseLogIdSetIndexRoute: typeof ApiV1SessionsSessionIdSetsExerciseLogIdSetIndexRoute
}

const ApiV1SessionsSessionIdRouteChildren: ApiV1SessionsSessionIdRouteChildren =
  {
    ApiV1SessionsSessionIdSetsExerciseLogIdSetIndexRoute:
      ApiV1SessionsSessionIdSetsExerciseLogIdSetIndexRoute,
  }

const ApiV1SessionsSessionIdRouteWithChildren =
  ApiV1SessionsSessionIdRoute._addFileChildren(
    ApiV1SessionsSessionIdRouteChildren,
  )

interface ApiV1SessionsRouteChildren {
  ApiV1SessionsSessionIdRoute: typeof ApiV1SessionsSessionIdRouteWithChildren
}

const ApiV1SessionsRouteChildren: ApiV1SessionsRouteChildren = {
  ApiV1SessionsSessionIdRoute: ApiV1SessionsSessionIdRouteWithChildren,
}

const ApiV1SessionsRouteWithChildren = ApiV1SessionsRoute._addFileChildren(
  ApiV1SessionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  HistoryRoute: HistoryRoute,
  ProgramRoute: ProgramRoute,
  SettingsRoute: SettingsRoute,
  TemplatesRoute: TemplatesRouteWithChildren,
  TodayRoute: TodayRoute,
  SessionsSessionIdRoute: SessionsSessionIdRouteWithChildren,
  ApiV1MeRoute: ApiV1MeRoute,
  ApiV1SessionsRoute: ApiV1SessionsRouteWithChildren,
  ApiV1TodayRoute: ApiV1TodayRoute,
  ApiV1AuthMagicLinkIntentRoute: ApiV1AuthMagicLinkIntentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
