import { Anchor } from '@mantine/core'
import { Text } from '~/components'
import {
  LEGAL_CONTACT_EMAIL,
  LegalDocument,
  LegalList,
  LegalSection,
} from './LegalDocument'

export function PrivacyPage() {
  return (
    <LegalDocument
      title="Privacy Policy"
      summary="This notice explains what personal data Sheetless collects, why it is used, where it is processed, and the controls available to you."
    >
      <LegalSection title="1. Information we collect">
        <LegalList
          items={[
            'Account data, including your user ID, email address, sign-in provider, authentication timestamps, and basic provider profile details.',
            'Profile and preference data, including display name, units, rounding, equipment, theme, training estimates, bodyweight, and sex when you choose to provide it.',
            'Training data, including programmes, custom templates, scheduled and completed workouts, exercises, sets, loads, reps, RPE or RIR, substitutions, notes, reflections, personal records, favorites, and progression decisions.',
            'Feedback you submit, together with the route, workout, or decision context needed to understand it.',
            'Essential technical data generated by authentication, hosting, security, and request logs. Sheetless does not currently operate a third-party advertising or product-analytics sink.',
          ]}
        />
      </LegalSection>

      <LegalSection title="2. How we use information">
        <LegalList
          items={[
            'Authenticate you and keep your account signed in.',
            'Save, display, and synchronize your training data while you are connected.',
            'Calculate deterministic workout prescriptions, progression decisions, history, and strength insights.',
            'Provide support, investigate feedback, prevent abuse, and maintain service security and reliability.',
            'Understand and improve the beta using feedback and aggregated operational information.',
          ]}
        />
        <Text component="p" size="sm" tone="dimmed" lh={1.6}>
          We use personal data only for purposes that are reasonably connected to operating
          Sheetless, fulfilling your request to use the service, meeting legal obligations, or
          protecting the service and its users.
        </Text>
      </LegalSection>

      <LegalSection title="3. Service providers and disclosures">
        <Text component="p" size="sm" tone="dimmed" lh={1.6}>
          Sheetless uses Supabase for authentication and database hosting, Railway for application
          hosting, Google when you choose Google sign-in, and Resend to deliver authentication
          email through Supabase. These providers process data for us under their own security and
          privacy terms and may process it in other countries.
        </Text>
        <Text component="p" size="sm" tone="dimmed" lh={1.6}>
          We do not sell or rent personal information and do not use it for targeted advertising.
          We may disclose information when required by law, to protect people or the service, or as
          part of a business transfer with appropriate notice and safeguards.
        </Text>
      </LegalSection>

      <LegalSection title="4. Retention and deletion">
        <Text component="p" size="sm" tone="dimmed" lh={1.6}>
          Account and training data is retained while your account remains active. You can
          permanently delete your account in Settings. Deletion removes your authentication
          identity and user-owned application rows, including custom programmes and training
          history. Limited information may remain temporarily in provider backups, security logs,
          or records that must be kept for legal purposes, then age out under the applicable
          retention schedule.
        </Text>
      </LegalSection>

      <LegalSection title="5. Your choices and rights">
        <LegalList
          items={[
            'Review and update supported profile and training information in the app.',
            'Download a machine-readable JSON copy of your account and training data from Settings.',
            'Delete your account and user-owned data from Settings after entering the required confirmation phrase.',
            'Ask for access, correction, restriction, objection, or other rights available under applicable law.',
            'Withdraw an OAuth connection through your provider. This does not automatically delete data already stored in Sheetless.',
          ]}
        />
        <Text component="p" size="sm" tone="dimmed" lh={1.6}>
          For a request the in-app controls do not cover, email{' '}
          <Anchor href={`mailto:${LEGAL_CONTACT_EMAIL}`}>{LEGAL_CONTACT_EMAIL}</Anchor>. We may need
          to verify that the request belongs to your account.
        </Text>
      </LegalSection>

      <LegalSection title="6. Cookies and local storage">
        <Text component="p" size="sm" tone="dimmed" lh={1.6}>
          Sheetless uses essential authentication cookies and limited browser storage required for
          sign-in, interface preferences, install/update behavior, and non-blocking walkthrough
          state. These are not used for advertising. Workout data is saved online; installing the
          app does not make workout logging an offline service.
        </Text>
      </LegalSection>

      <LegalSection title="7. Security and international processing">
        <Text component="p" size="sm" tone="dimmed" lh={1.6}>
          We use user-scoped database access, encrypted network connections, managed hosting, and
          operational controls designed to protect your data. No internet service can guarantee
          absolute security. Because our providers operate internationally, personal data may be
          processed outside your country with protections required by applicable law.
        </Text>
      </LegalSection>

      <LegalSection title="8. Age, changes, and contact">
        <Text component="p" size="sm" tone="dimmed" lh={1.6}>
          Sheetless is intended for people aged 18 or older and is not knowingly directed to
          children. We may update this notice as the beta, providers, or legal requirements change.
          Material changes will be shown in the app or otherwise communicated when appropriate.
          Questions can be sent to{' '}
          <Anchor href={`mailto:${LEGAL_CONTACT_EMAIL}`}>{LEGAL_CONTACT_EMAIL}</Anchor>.
        </Text>
      </LegalSection>
    </LegalDocument>
  )
}
