export { Text, type TextProps } from './Text'
export { Heading, type HeadingProps } from './Heading'
export { SectionLabel } from './SectionLabel'
export { StatValue } from './StatValue'
export { Caption } from './Caption'
export { toneColor, type Tone } from './tone'
