-- Expand the durable movement catalogue to the exact code-owned manifest.
-- This insert is intentionally exhaustive so legacy rows receive authoritative
-- metadata while the 81 new rows and 11 deprecated aliases land atomically.

insert into public.movements (
  id,
  name,
  category,
  equipment,
  variation_of,
  default_unit,
  is_competition,
  status,
  resistance_mode,
  required_equipment,
  pattern,
  primary_muscles,
  secondary_muscles,
  aliases,
  load_convention,
  replaced_by_movement_id,
  canonical_free_weight_movement_id
) values
  (
    'squat',
    'Squat',
    'lower',
    array['barbell', 'rack', 'plates']::text[],
    null,
    'kg',
    true,
    'active',
    'barbell',
    array['barbell', 'rack', 'plates']::text[],
    'squat',
    array['quads', 'glutes']::text[],
    array['hamstrings', 'core']::text[],
    array[]::text[],
    'total_external',
    null,
    null
  ),
  (
    'bench_press',
    'Bench Press',
    'upper',
    array['barbell', 'bench', 'plates']::text[],
    null,
    'kg',
    true,
    'active',
    'barbell',
    array['barbell', 'bench', 'plates']::text[],
    'horizontal_push',
    array['chest']::text[],
    array['triceps', 'shoulders']::text[],
    array[]::text[],
    'total_external',
    null,
    null
  ),
  (
    'deadlift',
    'Deadlift',
    'lower',
    array['barbell', 'plates']::text[],
    null,
    'kg',
    true,
    'active',
    'barbell',
    array['barbell', 'plates']::text[],
    'hinge',
    array['hamstrings', 'glutes']::text[],
    array['upper_back', 'core']::text[],
    array[]::text[],
    'total_external',
    null,
    null
  ),
  (
    'overhead_press',
    'Overhead Press',
    'upper',
    array['barbell', 'rack', 'plates']::text[],
    null,
    'kg',
    true,
    'active',
    'barbell',
    array['barbell', 'rack', 'plates']::text[],
    'vertical_push',
    array['shoulders']::text[],
    array['triceps', 'core']::text[],
    array[]::text[],
    'total_external',
    null,
    null
  ),
  (
    'front_squat',
    'Front Squat',
    'lower',
    array['barbell', 'rack', 'plates']::text[],
    'squat',
    'kg',
    false,
    'active',
    'barbell',
    array['barbell', 'rack', 'plates']::text[],
    'squat',
    array['quads', 'glutes']::text[],
    array['hamstrings', 'core']::text[],
    array[]::text[],
    'total_external',
    null,
    null
  ),
  (
    'close_grip_bench_press',
    'Close-Grip Bench Press',
    'upper',
    array['barbell', 'bench', 'plates']::text[],
    'bench_press',
    'kg',
    false,
    'active',
    'barbell',
    array['barbell', 'bench', 'plates']::text[],
    'horizontal_push',
    array['chest']::text[],
    array['triceps', 'shoulders']::text[],
    array[]::text[],
    'total_external',
    null,
    null
  ),
  (
    'stiff_leg_deadlift',
    'Stiff-Leg Deadlift',
    'hinge',
    array['barbell', 'plates']::text[],
    'deadlift',
    'kg',
    false,
    'active',
    'barbell',
    array['barbell', 'plates']::text[],
    'hinge',
    array['hamstrings', 'glutes']::text[],
    array['upper_back', 'core']::text[],
    array[]::text[],
    'total_external',
    null,
    null
  ),
  (
    'behind_neck_press',
    'Behind-the-Neck Press',
    'upper',
    array['barbell', 'rack', 'plates']::text[],
    'overhead_press',
    'kg',
    false,
    'active',
    'barbell',
    array['barbell', 'rack', 'plates']::text[],
    'vertical_push',
    array['shoulders']::text[],
    array['triceps', 'core']::text[],
    array[]::text[],
    'total_external',
    null,
    null
  ),
  (
    'pause_squat',
    'Pause Squat',
    'lower',
    array['barbell', 'rack', 'plates']::text[],
    'squat',
    'kg',
    false,
    'active',
    'barbell',
    array['barbell', 'rack', 'plates']::text[],
    'squat',
    array['quads', 'glutes']::text[],
    array['hamstrings', 'core']::text[],
    array[]::text[],
    'total_external',
    null,
    null
  ),
  (
    'board_press',
    'Board Press',
    'upper',
    array['barbell', 'bench', 'plates']::text[],
    'bench_press',
    'kg',
    false,
    'active',
    'barbell',
    array['barbell', 'bench', 'plates']::text[],
    'horizontal_push',
    array['chest']::text[],
    array['triceps', 'shoulders']::text[],
    array[]::text[],
    'total_external',
    null,
    null
  ),
  (
    'low_trap_bar_deadlift',
    'Low Trap Bar Deadlift',
    'hinge',
    array['specialty_bars', 'plates']::text[],
    'deadlift',
    'kg',
    false,
    'active',
    'specialty_bar',
    array['specialty_bar', 'plates']::text[],
    'hinge',
    array['hamstrings', 'glutes']::text[],
    array['upper_back', 'core']::text[],
    array[]::text[],
    'total_external',
    null,
    null
  ),
  (
    'seated_pin_press',
    'Seated Pin Press',
    'upper',
    array['barbell', 'rack', 'bench', 'plates']::text[],
    'overhead_press',
    'kg',
    false,
    'active',
    'barbell',
    array['barbell', 'rack', 'bench', 'plates']::text[],
    'vertical_push',
    array['shoulders']::text[],
    array['triceps', 'core']::text[],
    array[]::text[],
    'total_external',
    null,
    null
  ),
  (
    'romanian_deadlift',
    'Romanian Deadlift',
    'hinge',
    array['barbell', 'plates']::text[],
    'deadlift',
    'kg',
    false,
    'active',
    'barbell',
    array['barbell', 'plates']::text[],
    'hinge',
    array['hamstrings', 'glutes']::text[],
    array['upper_back', 'core']::text[],
    array[]::text[],
    'total_external',
    null,
    null
  ),
  (
    'seated_cable_row',
    'Seated Cable Row',
    'upper_back',
    array['cable', 'machine']::text[],
    null,
    'kg',
    false,
    'active',
    'cable',
    array['cable', 'machine']::text[],
    'horizontal_pull',
    array['upper_back']::text[],
    array['biceps', 'core']::text[],
    array[]::text[],
    'device_display',
    null,
    'barbell_row'
  ),
  (
    'machine_row',
    'Machine Row',
    'upper_back',
    array['machine']::text[],
    null,
    'kg',
    false,
    'active',
    'machine',
    array['machine']::text[],
    'horizontal_pull',
    array['upper_back']::text[],
    array['biceps', 'core']::text[],
    array[]::text[],
    'device_display',
    null,
    'chest_supported_dumbbell_row'
  ),
  (
    'one_arm_cable_row',
    'One-Arm Cable Row',
    'upper_back',
    array['cable']::text[],
    null,
    'kg',
    false,
    'active',
    'cable',
    array['cable']::text[],
    'horizontal_pull',
    array['upper_back']::text[],
    array['biceps', 'core']::text[],
    array[]::text[],
    'device_display',
    null,
    'dumbbell_row'
  ),
  (
    'chest_supported_row',
    'Chest-Supported Row',
    'upper_back',
    array['machine', 'dumbbells']::text[],
    null,
    'kg',
    false,
    'deprecated',
    null,
    array['machine', 'dumbbells']::text[],
    'horizontal_pull',
    array['upper_back']::text[],
    array['biceps', 'core']::text[],
    array[]::text[],
    'device_display',
    'chest_supported_dumbbell_row',
    'chest_supported_dumbbell_row'
  ),
  (
    'lat_pulldown',
    'Lat Pulldown',
    'upper_back',
    array['cable', 'machine']::text[],
    null,
    'kg',
    false,
    'active',
    'cable',
    array['cable', 'machine']::text[],
    'vertical_pull',
    array['upper_back']::text[],
    array['biceps', 'core']::text[],
    array[]::text[],
    'device_display',
    null,
    'pull_up'
  ),
  (
    'pull_up',
    'Pull-Up',
    'upper_back',
    array['bodyweight']::text[],
    null,
    'kg',
    false,
    'active',
    'bodyweight',
    array['bodyweight']::text[],
    'vertical_pull',
    array['upper_back']::text[],
    array['biceps', 'core']::text[],
    array[]::text[],
    'added_to_bodyweight',
    null,
    null
  ),
  (
    'machine_high_row',
    'Machine High Row',
    'upper_back',
    array['machine']::text[],
    null,
    'kg',
    false,
    'active',
    'machine',
    array['machine']::text[],
    'horizontal_pull',
    array['upper_back']::text[],
    array['biceps', 'core']::text[],
    array[]::text[],
    'device_display',
    null,
    'chest_supported_dumbbell_row'
  ),
  (
    'leg_press',
    'Leg Press',
    'lower',
    array['machine']::text[],
    'squat',
    'kg',
    false,
    'active',
    'machine',
    array['machine']::text[],
    'squat',
    array['quads', 'glutes']::text[],
    array['hamstrings', 'core']::text[],
    array[]::text[],
    'device_display',
    null,
    'goblet_squat'
  ),
  (
    'hack_squat',
    'Hack Squat',
    'lower',
    array['machine']::text[],
    'squat',
    'kg',
    false,
    'active',
    'machine',
    array['machine']::text[],
    'squat',
    array['quads', 'glutes']::text[],
    array['hamstrings', 'core']::text[],
    array[]::text[],
    'device_display',
    null,
    'goblet_squat'
  ),
  (
    'split_squat',
    'Split Squat',
    'lower',
    array['dumbbells', 'bodyweight']::text[],
    'squat',
    'kg',
    false,
    'deprecated',
    null,
    array['dumbbells', 'bodyweight']::text[],
    'lunge',
    array['quads', 'glutes']::text[],
    array['hamstrings', 'core']::text[],
    array[]::text[],
    'implement_weight',
    'dumbbell_split_squat',
    'dumbbell_split_squat'
  ),
  (
    'hamstring_curl',
    'Hamstring Curl',
    'posterior_chain',
    array['machine']::text[],
    null,
    'kg',
    false,
    'active',
    'machine',
    array['machine']::text[],
    'knee_flexion',
    array['hamstrings']::text[],
    array['glutes']::text[],
    array[]::text[],
    'device_display',
    null,
    'sliding_leg_curl'
  ),
  (
    'seated_leg_curl',
    'Seated Leg Curl',
    'posterior_chain',
    array['machine']::text[],
    null,
    'kg',
    false,
    'active',
    'machine',
    array['machine']::text[],
    'knee_flexion',
    array['hamstrings']::text[],
    array['glutes']::text[],
    array[]::text[],
    'device_display',
    null,
    'sliding_leg_curl'
  ),
  (
    'lying_leg_curl',
    'Lying Leg Curl',
    'posterior_chain',
    array['machine']::text[],
    null,
    'kg',
    false,
    'active',
    'machine',
    array['machine']::text[],
    'knee_flexion',
    array['hamstrings']::text[],
    array['glutes']::text[],
    array[]::text[],
    'device_display',
    null,
    'sliding_leg_curl'
  ),
  (
    'back_extension',
    'Back Extension',
    'posterior_chain',
    array['machine', 'bodyweight']::text[],
    null,
    'kg',
    false,
    'deprecated',
    null,
    array['machine', 'bodyweight']::text[],
    'hip_extension',
    array['glutes']::text[],
    array['hamstrings', 'core']::text[],
    array[]::text[],
    'device_display',
    'back_extension_45_degree',
    'back_extension_45_degree'
  ),
  (
    'reverse_hyperextension',
    'Reverse Hyperextension',
    'posterior_chain',
    array['machine']::text[],
    null,
    'kg',
    false,
    'active',
    'machine',
    array['machine']::text[],
    'hip_extension',
    array['glutes']::text[],
    array['hamstrings', 'core']::text[],
    array[]::text[],
    'device_display',
    null,
    'back_extension_45_degree'
  ),
  (
    'glute_ham_raise',
    'Glute-Ham Raise',
    'posterior_chain',
    array['machine', 'bodyweight']::text[],
    null,
    'kg',
    false,
    'active',
    'bodyweight',
    array['machine', 'bodyweight']::text[],
    'knee_flexion',
    array['hamstrings']::text[],
    array['glutes']::text[],
    array[]::text[],
    'bodyweight_only',
    null,
    'nordic_hamstring_curl'
  ),
  (
    'cable_crunch',
    'Cable Crunch',
    'core',
    array['cable']::text[],
    null,
    'kg',
    false,
    'active',
    'cable',
    array['cable']::text[],
    'trunk_flexion',
    array['core']::text[],
    array[]::text[],
    array[]::text[],
    'device_display',
    null,
    'weighted_sit_up'
  ),
  (
    'hanging_leg_raise',
    'Hanging Leg Raise',
    'core',
    array['bodyweight']::text[],
    null,
    'kg',
    false,
    'active',
    'bodyweight',
    array['bodyweight']::text[],
    'trunk_flexion',
    array['core']::text[],
    array[]::text[],
    array[]::text[],
    'bodyweight_only',
    null,
    null
  ),
  (
    'ab_wheel_rollout',
    'Ab Wheel Rollout',
    'core',
    array['bodyweight']::text[],
    null,
    'kg',
    false,
    'active',
    'bodyweight',
    array['ab_wheel']::text[],
    'trunk_flexion',
    array['core']::text[],
    array[]::text[],
    array[]::text[],
    'bodyweight_only',
    null,
    null
  ),
  (
    'dumbbell_row',
    'Dumbbell Row',
    'upper_back',
    array['dumbbells', 'bench']::text[],
    null,
    'kg',
    false,
    'active',
    'dumbbell',
    array['dumbbells', 'bench']::text[],
    'horizontal_pull',
    array['upper_back']::text[],
    array['biceps', 'core']::text[],
    array[]::text[],
    'implement_weight',
    null,
    null
  ),
  (
    'dumbbell_bench_press',
    'Dumbbell Bench Press',
    'upper',
    array['dumbbells', 'bench']::text[],
    'bench_press',
    'kg',
    false,
    'active',
    'dumbbell',
    array['dumbbells', 'bench']::text[],
    'horizontal_push',
    array['chest']::text[],
    array['triceps', 'shoulders']::text[],
    array[]::text[],
    'implement_weight',
    null,
    null
  ),
  (
    'incline_dumbbell_press',
    'Incline Dumbbell Press',
    'upper',
    array['dumbbells', 'bench']::text[],
    'bench_press',
    'kg',
    false,
    'active',
    'dumbbell',
    array['dumbbells', 'bench']::text[],
    'horizontal_push',
    array['chest']::text[],
    array['triceps', 'shoulders']::text[],
    array[]::text[],
    'implement_weight',
    null,
    null
  ),
  (
    'push_up',
    'Push-Up',
    'upper',
    array['bodyweight']::text[],
    'bench_press',
    'kg',
    false,
    'active',
    'bodyweight',
    array['bodyweight']::text[],
    'horizontal_push',
    array['chest']::text[],
    array['triceps', 'shoulders']::text[],
    array[]::text[],
    'bodyweight_only',
    null,
    null
  ),
  (
    'triceps_pressdown',
    'Triceps Pressdown',
    'upper',
    array['cable']::text[],
    null,
    'kg',
    false,
    'active',
    'cable',
    array['cable']::text[],
    'elbow_extension',
    array['triceps']::text[],
    array['shoulders']::text[],
    array[]::text[],
    'device_display',
    null,
    'dumbbell_triceps_kickback'
  ),
  (
    'overhead_triceps_extension',
    'Overhead Triceps Extension',
    'upper',
    array['cable', 'dumbbells']::text[],
    null,
    'kg',
    false,
    'deprecated',
    null,
    array['cable', 'dumbbells']::text[],
    'elbow_extension',
    array['triceps']::text[],
    array['shoulders']::text[],
    array[]::text[],
    'device_display',
    'dumbbell_overhead_triceps_extension',
    'dumbbell_overhead_triceps_extension'
  ),
  (
    'skullcrusher',
    'Skullcrusher',
    'upper',
    array['barbell', 'dumbbells', 'bench']::text[],
    null,
    'kg',
    false,
    'deprecated',
    null,
    array['barbell', 'dumbbells', 'bench']::text[],
    'elbow_extension',
    array['triceps']::text[],
    array['shoulders']::text[],
    array[]::text[],
    'total_external',
    'barbell_skullcrusher',
    'barbell_skullcrusher'
  ),
  (
    'face_pull',
    'Face Pull',
    'upper_back',
    array['cable']::text[],
    null,
    'kg',
    false,
    'active',
    'cable',
    array['cable']::text[],
    'shoulder_abduction',
    array['shoulders']::text[],
    array['upper_back']::text[],
    array[]::text[],
    'device_display',
    null,
    'dumbbell_rear_delt_fly'
  ),
  (
    'rear_delt_fly',
    'Rear Delt Fly',
    'upper_back',
    array['dumbbells', 'machine']::text[],
    null,
    'kg',
    false,
    'deprecated',
    null,
    array['dumbbells', 'machine']::text[],
    'shoulder_abduction',
    array['shoulders']::text[],
    array['upper_back']::text[],
    array[]::text[],
    'device_display',
    'dumbbell_rear_delt_fly',
    'dumbbell_rear_delt_fly'
  ),
  (
    'safety_bar_squat',
    'Safety Bar Squat',
    'lower',
    array['specialty_bars', 'rack', 'plates']::text[],
    'squat',
    'kg',
    false,
    'active',
    'specialty_bar',
    array['specialty_bar', 'rack', 'plates']::text[],
    'squat',
    array['quads', 'glutes']::text[],
    array['hamstrings', 'core']::text[],
    array[]::text[],
    'total_external',
    null,
    null
  ),
  (
    'good_morning',
    'Good Morning',
    'hinge',
    array['barbell', 'rack', 'plates']::text[],
    'deadlift',
    'kg',
    false,
    'active',
    'barbell',
    array['barbell', 'rack', 'plates']::text[],
    'hinge',
    array['hamstrings', 'glutes']::text[],
    array['upper_back', 'core']::text[],
    array[]::text[],
    'total_external',
    null,
    null
  ),
  (
    'seated_dumbbell_press',
    'Seated Dumbbell Press',
    'upper',
    array['dumbbells', 'bench']::text[],
    'overhead_press',
    'kg',
    false,
    'active',
    'dumbbell',
    array['dumbbells', 'bench']::text[],
    'vertical_push',
    array['shoulders']::text[],
    array['triceps', 'core']::text[],
    array[]::text[],
    'implement_weight',
    null,
    null
  ),
  (
    'wide_grip_bench_press',
    'Wide-Grip Bench Press',
    'upper',
    array['barbell', 'bench', 'plates']::text[],
    'bench_press',
    'kg',
    false,
    'active',
    'barbell',
    array['barbell', 'bench', 'plates']::text[],
    'horizontal_push',
    array['chest']::text[],
    array['triceps', 'shoulders']::text[],
    array[]::text[],
    'total_external',
    null,
    null
  ),
  (
    'pause_bench_press',
    'Pause Bench Press',
    'upper',
    array['barbell', 'bench', 'plates']::text[],
    'bench_press',
    'kg',
    false,
    'active',
    'barbell',
    array['barbell', 'bench', 'plates']::text[],
    'horizontal_push',
    array['chest']::text[],
    array['triceps', 'shoulders']::text[],
    array[]::text[],
    'total_external',
    null,
    null
  ),
  (
    'floor_press',
    'Floor Press',
    'upper',
    array['barbell', 'plates']::text[],
    'bench_press',
    'kg',
    false,
    'active',
    'barbell',
    array['barbell', 'plates']::text[],
    'horizontal_push',
    array['chest']::text[],
    array['triceps', 'shoulders']::text[],
    array[]::text[],
    'total_external',
    null,
    null
  ),
  (
    'incline_bench_press',
    'Incline Bench Press',
    'upper',
    array['barbell', 'bench', 'plates']::text[],
    'bench_press',
    'kg',
    false,
    'active',
    'barbell',
    array['barbell', 'bench', 'plates']::text[],
    'horizontal_push',
    array['chest']::text[],
    array['triceps', 'shoulders']::text[],
    array[]::text[],
    'total_external',
    null,
    null
  ),
  (
    'wide_stance_squat',
    'Wide-Stance Squat',
    'lower',
    array['barbell', 'rack', 'plates']::text[],
    'squat',
    'kg',
    false,
    'active',
    'barbell',
    array['barbell', 'rack', 'plates']::text[],
    'squat',
    array['quads', 'glutes']::text[],
    array['hamstrings', 'core']::text[],
    array[]::text[],
    'total_external',
    null,
    null
  ),
  (
    'high_box_squat',
    'High Box Squat',
    'lower',
    array['barbell', 'rack', 'box', 'plates']::text[],
    'squat',
    'kg',
    false,
    'active',
    'barbell',
    array['barbell', 'rack', 'box', 'plates']::text[],
    'squat',
    array['quads', 'glutes']::text[],
    array['hamstrings', 'core']::text[],
    array[]::text[],
    'total_external',
    null,
    null
  ),
  (
    'lunge',
    'Lunge',
    'lower',
    array['dumbbells', 'bodyweight']::text[],
    'squat',
    'kg',
    false,
    'deprecated',
    null,
    array['dumbbells', 'bodyweight']::text[],
    'lunge',
    array['quads', 'glutes']::text[],
    array['hamstrings', 'core']::text[],
    array[]::text[],
    'implement_weight',
    'dumbbell_lunge',
    'dumbbell_lunge'
  ),
  (
    'wide_grip_overhead_press',
    'Wide-Grip Overhead Press',
    'upper',
    array['barbell', 'rack', 'plates']::text[],
    'overhead_press',
    'kg',
    false,
    'active',
    'barbell',
    array['barbell', 'rack', 'plates']::text[],
    'vertical_push',
    array['shoulders']::text[],
    array['triceps', 'core']::text[],
    array[]::text[],
    'total_external',
    null,
    null
  ),
  (
    'push_press',
    'Push Press',
    'upper',
    array['barbell', 'rack', 'plates']::text[],
    'overhead_press',
    'kg',
    false,
    'active',
    'barbell',
    array['barbell', 'rack', 'plates']::text[],
    'vertical_push',
    array['shoulders']::text[],
    array['triceps', 'core']::text[],
    array[]::text[],
    'total_external',
    null,
    null
  ),
  (
    'standing_pin_press',
    'Standing Pin Press',
    'upper',
    array['barbell', 'rack', 'plates']::text[],
    'overhead_press',
    'kg',
    false,
    'active',
    'barbell',
    array['barbell', 'rack', 'plates']::text[],
    'vertical_push',
    array['shoulders']::text[],
    array['triceps', 'core']::text[],
    array[]::text[],
    'total_external',
    null,
    null
  ),
  (
    'block_deadlift',
    'Block Deadlift',
    'hinge',
    array['barbell', 'plates', 'blocks']::text[],
    'deadlift',
    'kg',
    false,
    'active',
    'barbell',
    array['barbell', 'plates', 'box']::text[],
    'hinge',
    array['hamstrings', 'glutes']::text[],
    array['upper_back', 'core']::text[],
    array[]::text[],
    'total_external',
    null,
    null
  ),
  (
    'sumo_deadlift',
    'Sumo Deadlift',
    'hinge',
    array['barbell', 'plates']::text[],
    'deadlift',
    'kg',
    false,
    'active',
    'barbell',
    array['barbell', 'plates']::text[],
    'hinge',
    array['hamstrings', 'glutes']::text[],
    array['upper_back', 'core']::text[],
    array[]::text[],
    'total_external',
    null,
    null
  ),
  (
    'barbell_row',
    'Barbell Row',
    'upper_back',
    array['barbell', 'plates']::text[],
    null,
    'kg',
    false,
    'active',
    'barbell',
    array['barbell', 'plates']::text[],
    'horizontal_pull',
    array['upper_back']::text[],
    array['biceps', 'core']::text[],
    array[]::text[],
    'total_external',
    null,
    null
  ),
  (
    't_bar_row',
    'T-Bar Row',
    'upper_back',
    array['barbell', 'plates', 'machine']::text[],
    null,
    'kg',
    false,
    'deprecated',
    null,
    array['barbell', 'plates', 'machine']::text[],
    'horizontal_pull',
    array['upper_back']::text[],
    array['biceps', 'core']::text[],
    array[]::text[],
    'device_display',
    'landmine_t_bar_row',
    'landmine_t_bar_row'
  ),
  (
    'pendlay_row',
    'Pendlay Row',
    'upper_back',
    array['barbell', 'plates']::text[],
    null,
    'kg',
    false,
    'active',
    'barbell',
    array['barbell', 'plates']::text[],
    'horizontal_pull',
    array['upper_back']::text[],
    array['biceps', 'core']::text[],
    array[]::text[],
    'total_external',
    null,
    null
  ),
  (
    'kroc_row',
    'Kroc Row',
    'upper_back',
    array['dumbbells']::text[],
    null,
    'kg',
    false,
    'active',
    'dumbbell',
    array['dumbbells']::text[],
    'horizontal_pull',
    array['upper_back']::text[],
    array['biceps', 'core']::text[],
    array[]::text[],
    'implement_weight',
    null,
    null
  ),
  (
    'chin_up',
    'Chin-Up',
    'upper_back',
    array['bodyweight']::text[],
    null,
    'kg',
    false,
    'active',
    'bodyweight',
    array['bodyweight']::text[],
    'vertical_pull',
    array['upper_back']::text[],
    array['biceps', 'core']::text[],
    array[]::text[],
    'added_to_bodyweight',
    null,
    null
  ),
  (
    'v_handle_pulldown',
    'V-Handle Pulldown',
    'upper_back',
    array['cable', 'machine']::text[],
    null,
    'kg',
    false,
    'active',
    'cable',
    array['cable', 'machine']::text[],
    'vertical_pull',
    array['upper_back']::text[],
    array['biceps', 'core']::text[],
    array[]::text[],
    'device_display',
    null,
    'neutral_grip_pull_up'
  ),
  (
    'upright_row',
    'Upright Row',
    'upper_back',
    array['barbell', 'dumbbells', 'cable']::text[],
    null,
    'kg',
    false,
    'deprecated',
    null,
    array['barbell', 'dumbbells', 'cable']::text[],
    'shoulder_abduction',
    array['shoulders']::text[],
    array['upper_back']::text[],
    array[]::text[],
    'device_display',
    'barbell_upright_row',
    'barbell_upright_row'
  ),
  (
    'barbell_curl',
    'Barbell Curl',
    'upper',
    array['barbell', 'plates']::text[],
    null,
    'kg',
    false,
    'active',
    'barbell',
    array['barbell', 'plates']::text[],
    'elbow_flexion',
    array['biceps']::text[],
    array['forearms']::text[],
    array[]::text[],
    'total_external',
    null,
    null
  ),
  (
    'dumbbell_curl',
    'Dumbbell Curl',
    'upper',
    array['dumbbells']::text[],
    null,
    'kg',
    false,
    'active',
    'dumbbell',
    array['dumbbells']::text[],
    'elbow_flexion',
    array['biceps']::text[],
    array['forearms']::text[],
    array[]::text[],
    'implement_weight',
    null,
    null
  ),
  (
    'rope_pressdown',
    'Rope Pressdown',
    'upper',
    array['cable']::text[],
    null,
    'kg',
    false,
    'active',
    'cable',
    array['cable']::text[],
    'elbow_extension',
    array['triceps']::text[],
    array['shoulders']::text[],
    array[]::text[],
    'device_display',
    null,
    'dumbbell_triceps_kickback'
  ),
  (
    'jm_press',
    'JM Press',
    'upper',
    array['barbell', 'bench', 'plates']::text[],
    null,
    'kg',
    false,
    'active',
    'barbell',
    array['barbell', 'bench', 'plates']::text[],
    'elbow_extension',
    array['triceps']::text[],
    array['shoulders']::text[],
    array[]::text[],
    'total_external',
    null,
    null
  ),
  (
    'french_press',
    'French Press',
    'upper',
    array['barbell', 'dumbbells']::text[],
    null,
    'kg',
    false,
    'deprecated',
    null,
    array['barbell', 'dumbbells']::text[],
    'elbow_extension',
    array['triceps']::text[],
    array['shoulders']::text[],
    array[]::text[],
    'total_external',
    'barbell_french_press',
    'barbell_french_press'
  ),
  (
    'sit_up',
    'Sit-Up',
    'core',
    array['bodyweight']::text[],
    null,
    'kg',
    false,
    'active',
    'bodyweight',
    array['bodyweight']::text[],
    'trunk_flexion',
    array['core']::text[],
    array[]::text[],
    array[]::text[],
    'bodyweight_only',
    null,
    null
  ),
  (
    'side_bend',
    'Side Bend',
    'core',
    array['dumbbells', 'cable']::text[],
    null,
    'kg',
    false,
    'deprecated',
    null,
    array['dumbbells', 'cable']::text[],
    'trunk_lateral_flexion',
    array['core']::text[],
    array[]::text[],
    array[]::text[],
    'device_display',
    'dumbbell_side_bend',
    'dumbbell_side_bend'
  ),
  (
    'chest_supported_dumbbell_row',
    'Chest-Supported Dumbbell Row',
    'upper_back',
    array['dumbbells', 'bench']::text[],
    null,
    'kg',
    false,
    'active',
    'dumbbell',
    array['dumbbells', 'bench']::text[],
    'horizontal_pull',
    array['upper_back']::text[],
    array['biceps', 'core']::text[],
    array['chest-supported row']::text[],
    'implement_weight',
    null,
    null
  ),
  (
    'machine_chest_supported_row',
    'Machine Chest-Supported Row',
    'upper_back',
    array['machine']::text[],
    null,
    'kg',
    false,
    'active',
    'machine',
    array['machine']::text[],
    'horizontal_pull',
    array['upper_back']::text[],
    array['biceps', 'core']::text[],
    array[]::text[],
    'device_display',
    null,
    'chest_supported_dumbbell_row'
  ),
  (
    'landmine_t_bar_row',
    'Landmine T-Bar Row',
    'upper_back',
    array['barbell', 'plates', 'landmine']::text[],
    null,
    'kg',
    false,
    'active',
    'barbell',
    array['barbell', 'plates', 'landmine']::text[],
    'horizontal_pull',
    array['upper_back']::text[],
    array['biceps', 'core']::text[],
    array['t-bar row']::text[],
    'total_external',
    null,
    null
  ),
  (
    'machine_t_bar_row',
    'Machine T-Bar Row',
    'upper_back',
    array['machine']::text[],
    null,
    'kg',
    false,
    'active',
    'machine',
    array['machine']::text[],
    'horizontal_pull',
    array['upper_back']::text[],
    array['biceps', 'core']::text[],
    array[]::text[],
    'device_display',
    null,
    'landmine_t_bar_row'
  ),
  (
    'dumbbell_split_squat',
    'Dumbbell Split Squat',
    'lower',
    array['dumbbells']::text[],
    'squat',
    'kg',
    false,
    'active',
    'dumbbell',
    array['dumbbells']::text[],
    'lunge',
    array['quads', 'glutes']::text[],
    array['hamstrings', 'core']::text[],
    array['split squat']::text[],
    'implement_weight',
    null,
    null
  ),
  (
    'bodyweight_split_squat',
    'Bodyweight Split Squat',
    'lower',
    array['bodyweight']::text[],
    'squat',
    'kg',
    false,
    'active',
    'bodyweight',
    array['bodyweight']::text[],
    'lunge',
    array['quads', 'glutes']::text[],
    array['hamstrings', 'core']::text[],
    array[]::text[],
    'bodyweight_only',
    null,
    null
  ),
  (
    'dumbbell_lunge',
    'Dumbbell Lunge',
    'lower',
    array['dumbbells']::text[],
    'squat',
    'kg',
    false,
    'active',
    'dumbbell',
    array['dumbbells']::text[],
    'lunge',
    array['quads', 'glutes']::text[],
    array['hamstrings', 'core']::text[],
    array['lunge']::text[],
    'implement_weight',
    null,
    null
  ),
  (
    'bodyweight_lunge',
    'Bodyweight Lunge',
    'lower',
    array['bodyweight']::text[],
    'squat',
    'kg',
    false,
    'active',
    'bodyweight',
    array['bodyweight']::text[],
    'lunge',
    array['quads', 'glutes']::text[],
    array['hamstrings', 'core']::text[],
    array[]::text[],
    'bodyweight_only',
    null,
    null
  ),
  (
    'back_extension_45_degree',
    '45-Degree Back Extension',
    'posterior_chain',
    array['bodyweight', 'machine']::text[],
    null,
    'kg',
    false,
    'active',
    'bodyweight',
    array['bodyweight', 'machine']::text[],
    'hip_extension',
    array['glutes']::text[],
    array['hamstrings', 'core']::text[],
    array['back extension', 'hyperextension']::text[],
    'bodyweight_only',
    null,
    null
  ),
  (
    'machine_back_extension',
    'Machine Back Extension',
    'posterior_chain',
    array['machine']::text[],
    null,
    'kg',
    false,
    'active',
    'machine',
    array['machine']::text[],
    'hip_extension',
    array['glutes']::text[],
    array['hamstrings', 'core']::text[],
    array[]::text[],
    'device_display',
    null,
    null
  ),
  (
    'dumbbell_overhead_triceps_extension',
    'Dumbbell Overhead Triceps Extension',
    'upper',
    array['dumbbells']::text[],
    null,
    'kg',
    false,
    'active',
    'dumbbell',
    array['dumbbells']::text[],
    'elbow_extension',
    array['triceps']::text[],
    array['shoulders']::text[],
    array['overhead triceps extension']::text[],
    'implement_weight',
    null,
    null
  ),
  (
    'cable_overhead_triceps_extension',
    'Cable Overhead Triceps Extension',
    'upper',
    array['cable']::text[],
    null,
    'kg',
    false,
    'active',
    'cable',
    array['cable']::text[],
    'elbow_extension',
    array['triceps']::text[],
    array['shoulders']::text[],
    array[]::text[],
    'device_display',
    null,
    'dumbbell_overhead_triceps_extension'
  ),
  (
    'barbell_skullcrusher',
    'Barbell Skullcrusher',
    'upper',
    array['barbell', 'bench', 'plates']::text[],
    null,
    'kg',
    false,
    'active',
    'barbell',
    array['barbell', 'bench', 'plates']::text[],
    'elbow_extension',
    array['triceps']::text[],
    array['shoulders']::text[],
    array['skullcrusher']::text[],
    'total_external',
    null,
    null
  ),
  (
    'dumbbell_skullcrusher',
    'Dumbbell Skullcrusher',
    'upper',
    array['dumbbells', 'bench']::text[],
    null,
    'kg',
    false,
    'active',
    'dumbbell',
    array['dumbbells', 'bench']::text[],
    'elbow_extension',
    array['triceps']::text[],
    array['shoulders']::text[],
    array[]::text[],
    'implement_weight',
    null,
    null
  ),
  (
    'barbell_french_press',
    'Barbell French Press',
    'upper',
    array['barbell', 'plates']::text[],
    null,
    'kg',
    false,
    'active',
    'barbell',
    array['barbell', 'plates']::text[],
    'elbow_extension',
    array['triceps']::text[],
    array['shoulders']::text[],
    array['french press']::text[],
    'total_external',
    null,
    null
  ),
  (
    'dumbbell_french_press',
    'Dumbbell French Press',
    'upper',
    array['dumbbells']::text[],
    null,
    'kg',
    false,
    'active',
    'dumbbell',
    array['dumbbells']::text[],
    'elbow_extension',
    array['triceps']::text[],
    array['shoulders']::text[],
    array[]::text[],
    'implement_weight',
    null,
    null
  ),
  (
    'dumbbell_rear_delt_fly',
    'Dumbbell Rear Delt Fly',
    'upper_back',
    array['dumbbells']::text[],
    null,
    'kg',
    false,
    'active',
    'dumbbell',
    array['dumbbells']::text[],
    'shoulder_abduction',
    array['shoulders']::text[],
    array['upper_back']::text[],
    array['rear delt fly']::text[],
    'implement_weight',
    null,
    null
  ),
  (
    'reverse_pec_deck',
    'Reverse Pec Deck',
    'upper_back',
    array['machine']::text[],
    null,
    'kg',
    false,
    'active',
    'machine',
    array['machine']::text[],
    'shoulder_abduction',
    array['shoulders']::text[],
    array['upper_back']::text[],
    array[]::text[],
    'device_display',
    null,
    'dumbbell_rear_delt_fly'
  ),
  (
    'barbell_upright_row',
    'Barbell Upright Row',
    'upper_back',
    array['barbell', 'plates']::text[],
    null,
    'kg',
    false,
    'active',
    'barbell',
    array['barbell', 'plates']::text[],
    'shoulder_abduction',
    array['shoulders']::text[],
    array['upper_back']::text[],
    array['upright row']::text[],
    'total_external',
    null,
    null
  ),
  (
    'dumbbell_upright_row',
    'Dumbbell Upright Row',
    'upper_back',
    array['dumbbells']::text[],
    null,
    'kg',
    false,
    'active',
    'dumbbell',
    array['dumbbells']::text[],
    'shoulder_abduction',
    array['shoulders']::text[],
    array['upper_back']::text[],
    array[]::text[],
    'implement_weight',
    null,
    null
  ),
  (
    'cable_upright_row',
    'Cable Upright Row',
    'upper_back',
    array['cable']::text[],
    null,
    'kg',
    false,
    'active',
    'cable',
    array['cable']::text[],
    'shoulder_abduction',
    array['shoulders']::text[],
    array['upper_back']::text[],
    array[]::text[],
    'device_display',
    null,
    'barbell_upright_row'
  ),
  (
    'dumbbell_side_bend',
    'Dumbbell Side Bend',
    'core',
    array['dumbbells']::text[],
    null,
    'kg',
    false,
    'active',
    'dumbbell',
    array['dumbbells']::text[],
    'trunk_lateral_flexion',
    array['core']::text[],
    array[]::text[],
    array['side bend']::text[],
    'implement_weight',
    null,
    null
  ),
  (
    'cable_side_bend',
    'Cable Side Bend',
    'core',
    array['cable']::text[],
    null,
    'kg',
    false,
    'active',
    'cable',
    array['cable']::text[],
    'trunk_lateral_flexion',
    array['core']::text[],
    array[]::text[],
    array[]::text[],
    'device_display',
    null,
    'dumbbell_side_bend'
  ),
  (
    'goblet_squat',
    'Goblet Squat',
    'lower',
    array['dumbbells']::text[],
    'squat',
    'kg',
    false,
    'active',
    'dumbbell',
    array['dumbbells']::text[],
    'squat',
    array['quads', 'glutes']::text[],
    array['hamstrings', 'core']::text[],
    array[]::text[],
    'implement_weight',
    null,
    null
  ),
  (
    'dumbbell_bulgarian_split_squat',
    'Dumbbell Bulgarian Split Squat',
    'lower',
    array['dumbbells', 'bench']::text[],
    'squat',
    'kg',
    false,
    'active',
    'dumbbell',
    array['dumbbells', 'bench']::text[],
    'lunge',
    array['quads', 'glutes']::text[],
    array['hamstrings', 'core']::text[],
    array[]::text[],
    'implement_weight',
    null,
    null
  ),
  (
    'dumbbell_step_up',
    'Dumbbell Step-Up',
    'lower',
    array['dumbbells', 'box']::text[],
    'squat',
    'kg',
    false,
    'active',
    'dumbbell',
    array['dumbbells', 'box']::text[],
    'lunge',
    array['quads', 'glutes']::text[],
    array['hamstrings', 'core']::text[],
    array[]::text[],
    'implement_weight',
    null,
    null
  ),
  (
    'leg_extension',
    'Leg Extension',
    'lower',
    array['machine']::text[],
    null,
    'kg',
    false,
    'active',
    'machine',
    array['machine']::text[],
    'knee_extension',
    array['quads']::text[],
    array[]::text[],
    array[]::text[],
    'device_display',
    null,
    'goblet_squat'
  ),
  (
    'standing_dumbbell_calf_raise',
    'Standing Dumbbell Calf Raise',
    'lower',
    array['dumbbells']::text[],
    null,
    'kg',
    false,
    'active',
    'dumbbell',
    array['dumbbells']::text[],
    'calf_raise',
    array['calves']::text[],
    array[]::text[],
    array[]::text[],
    'implement_weight',
    null,
    null
  ),
  (
    'seated_dumbbell_calf_raise',
    'Seated Dumbbell Calf Raise',
    'lower',
    array['dumbbells', 'bench']::text[],
    null,
    'kg',
    false,
    'active',
    'dumbbell',
    array['dumbbells', 'bench']::text[],
    'calf_raise',
    array['calves']::text[],
    array[]::text[],
    array[]::text[],
    'implement_weight',
    null,
    null
  ),
  (
    'standing_machine_calf_raise',
    'Standing Machine Calf Raise',
    'lower',
    array['machine']::text[],
    null,
    'kg',
    false,
    'active',
    'machine',
    array['machine']::text[],
    'calf_raise',
    array['calves']::text[],
    array[]::text[],
    array[]::text[],
    'device_display',
    null,
    'standing_dumbbell_calf_raise'
  ),
  (
    'seated_machine_calf_raise',
    'Seated Machine Calf Raise',
    'lower',
    array['machine']::text[],
    null,
    'kg',
    false,
    'active',
    'machine',
    array['machine']::text[],
    'calf_raise',
    array['calves']::text[],
    array[]::text[],
    array[]::text[],
    'device_display',
    null,
    'seated_dumbbell_calf_raise'
  ),
  (
    'dumbbell_romanian_deadlift',
    'Dumbbell Romanian Deadlift',
    'hinge',
    array['dumbbells']::text[],
    'deadlift',
    'kg',
    false,
    'active',
    'dumbbell',
    array['dumbbells']::text[],
    'hinge',
    array['hamstrings', 'glutes']::text[],
    array['upper_back', 'core']::text[],
    array[]::text[],
    'implement_weight',
    null,
    null
  ),
  (
    'single_leg_dumbbell_romanian_deadlift',
    'Single-Leg Dumbbell Romanian Deadlift',
    'hinge',
    array['dumbbells']::text[],
    'deadlift',
    'kg',
    false,
    'active',
    'dumbbell',
    array['dumbbells']::text[],
    'hinge',
    array['hamstrings', 'glutes']::text[],
    array['upper_back', 'core']::text[],
    array[]::text[],
    'implement_weight',
    null,
    null
  ),
  (
    'barbell_hip_thrust',
    'Barbell Hip Thrust',
    'posterior_chain',
    array['barbell', 'bench', 'plates']::text[],
    null,
    'kg',
    false,
    'active',
    'barbell',
    array['barbell', 'bench', 'plates']::text[],
    'hip_extension',
    array['glutes']::text[],
    array['hamstrings', 'core']::text[],
    array[]::text[],
    'total_external',
    null,
    null
  ),
  (
    'sliding_leg_curl',
    'Sliding Leg Curl',
    'posterior_chain',
    array['bodyweight', 'sliders']::text[],
    null,
    'kg',
    false,
    'active',
    'bodyweight',
    array['bodyweight', 'sliders']::text[],
    'knee_flexion',
    array['hamstrings']::text[],
    array['glutes']::text[],
    array[]::text[],
    'bodyweight_only',
    null,
    null
  ),
  (
    'nordic_hamstring_curl',
    'Nordic Hamstring Curl',
    'posterior_chain',
    array['bodyweight']::text[],
    null,
    'kg',
    false,
    'active',
    'bodyweight',
    array['bodyweight']::text[],
    'knee_flexion',
    array['hamstrings']::text[],
    array['glutes']::text[],
    array[]::text[],
    'bodyweight_only',
    null,
    null
  ),
  (
    'hip_thrust_machine',
    'Hip Thrust Machine',
    'posterior_chain',
    array['machine']::text[],
    null,
    'kg',
    false,
    'active',
    'machine',
    array['machine']::text[],
    'hip_extension',
    array['glutes']::text[],
    array['hamstrings', 'core']::text[],
    array[]::text[],
    'device_display',
    null,
    'barbell_hip_thrust'
  ),
  (
    'dumbbell_fly',
    'Dumbbell Fly',
    'upper',
    array['dumbbells', 'bench']::text[],
    'bench_press',
    'kg',
    false,
    'active',
    'dumbbell',
    array['dumbbells', 'bench']::text[],
    'horizontal_push',
    array['chest']::text[],
    array['triceps', 'shoulders']::text[],
    array[]::text[],
    'implement_weight',
    null,
    null
  ),
  (
    'dip',
    'Dip',
    'upper',
    array['bodyweight', 'dip_bars']::text[],
    'bench_press',
    'kg',
    false,
    'active',
    'bodyweight',
    array['bodyweight', 'dip_bars']::text[],
    'horizontal_push',
    array['chest']::text[],
    array['triceps', 'shoulders']::text[],
    array[]::text[],
    'added_to_bodyweight',
    null,
    null
  ),
  (
    'machine_chest_press',
    'Machine Chest Press',
    'upper',
    array['machine']::text[],
    'bench_press',
    'kg',
    false,
    'active',
    'machine',
    array['machine']::text[],
    'horizontal_push',
    array['chest']::text[],
    array['triceps', 'shoulders']::text[],
    array[]::text[],
    'device_display',
    null,
    'dumbbell_bench_press'
  ),
  (
    'pec_deck',
    'Pec Deck',
    'upper',
    array['machine']::text[],
    'bench_press',
    'kg',
    false,
    'active',
    'machine',
    array['machine']::text[],
    'horizontal_push',
    array['chest']::text[],
    array['triceps', 'shoulders']::text[],
    array[]::text[],
    'device_display',
    null,
    'dumbbell_fly'
  ),
  (
    'standing_dumbbell_press',
    'Standing Dumbbell Press',
    'upper',
    array['dumbbells']::text[],
    'overhead_press',
    'kg',
    false,
    'active',
    'dumbbell',
    array['dumbbells']::text[],
    'vertical_push',
    array['shoulders']::text[],
    array['triceps', 'core']::text[],
    array[]::text[],
    'implement_weight',
    null,
    null
  ),
  (
    'dumbbell_lateral_raise',
    'Dumbbell Lateral Raise',
    'upper',
    array['dumbbells']::text[],
    null,
    'kg',
    false,
    'active',
    'dumbbell',
    array['dumbbells']::text[],
    'shoulder_abduction',
    array['shoulders']::text[],
    array['upper_back']::text[],
    array[]::text[],
    'implement_weight',
    null,
    null
  ),
  (
    'cable_lateral_raise',
    'Cable Lateral Raise',
    'upper',
    array['cable']::text[],
    null,
    'kg',
    false,
    'active',
    'cable',
    array['cable']::text[],
    'shoulder_abduction',
    array['shoulders']::text[],
    array['upper_back']::text[],
    array[]::text[],
    'device_display',
    null,
    'dumbbell_lateral_raise'
  ),
  (
    'seal_row',
    'Seal Row',
    'upper_back',
    array['barbell', 'bench', 'plates']::text[],
    null,
    'kg',
    false,
    'active',
    'barbell',
    array['barbell', 'bench', 'plates']::text[],
    'horizontal_pull',
    array['upper_back']::text[],
    array['biceps', 'core']::text[],
    array[]::text[],
    'total_external',
    null,
    null
  ),
  (
    'inverted_row',
    'Inverted Row',
    'upper_back',
    array['bodyweight', 'rack']::text[],
    null,
    'kg',
    false,
    'active',
    'bodyweight',
    array['bodyweight', 'rack']::text[],
    'horizontal_pull',
    array['upper_back']::text[],
    array['biceps', 'core']::text[],
    array[]::text[],
    'bodyweight_only',
    null,
    null
  ),
  (
    'neutral_grip_pull_up',
    'Neutral-Grip Pull-Up',
    'upper_back',
    array['bodyweight', 'pull_up_bar']::text[],
    null,
    'kg',
    false,
    'active',
    'bodyweight',
    array['bodyweight', 'pull_up_bar']::text[],
    'vertical_pull',
    array['upper_back']::text[],
    array['biceps', 'core']::text[],
    array[]::text[],
    'added_to_bodyweight',
    null,
    null
  ),
  (
    'dumbbell_pullover',
    'Dumbbell Pullover',
    'upper_back',
    array['dumbbells', 'bench']::text[],
    null,
    'kg',
    false,
    'active',
    'dumbbell',
    array['dumbbells', 'bench']::text[],
    'vertical_pull',
    array['upper_back']::text[],
    array['biceps', 'core']::text[],
    array[]::text[],
    'implement_weight',
    null,
    null
  ),
  (
    'barbell_shrug',
    'Barbell Shrug',
    'upper_back',
    array['barbell', 'plates']::text[],
    null,
    'kg',
    false,
    'active',
    'barbell',
    array['barbell', 'plates']::text[],
    'scapular_elevation',
    array['upper_back']::text[],
    array['forearms']::text[],
    array[]::text[],
    'total_external',
    null,
    null
  ),
  (
    'straight_arm_cable_pulldown',
    'Straight-Arm Cable Pulldown',
    'upper_back',
    array['cable']::text[],
    null,
    'kg',
    false,
    'active',
    'cable',
    array['cable']::text[],
    'vertical_pull',
    array['upper_back']::text[],
    array['biceps', 'core']::text[],
    array[]::text[],
    'device_display',
    null,
    'dumbbell_pullover'
  ),
  (
    'hammer_curl',
    'Hammer Curl',
    'upper',
    array['dumbbells']::text[],
    null,
    'kg',
    false,
    'active',
    'dumbbell',
    array['dumbbells']::text[],
    'elbow_flexion',
    array['biceps']::text[],
    array['forearms']::text[],
    array[]::text[],
    'implement_weight',
    null,
    null
  ),
  (
    'incline_dumbbell_curl',
    'Incline Dumbbell Curl',
    'upper',
    array['dumbbells', 'bench']::text[],
    null,
    'kg',
    false,
    'active',
    'dumbbell',
    array['dumbbells', 'bench']::text[],
    'elbow_flexion',
    array['biceps']::text[],
    array['forearms']::text[],
    array[]::text[],
    'implement_weight',
    null,
    null
  ),
  (
    'ez_bar_preacher_curl',
    'EZ-Bar Preacher Curl',
    'upper',
    array['specialty_bars', 'bench', 'plates']::text[],
    null,
    'kg',
    false,
    'active',
    'specialty_bar',
    array['specialty_bar', 'bench', 'plates']::text[],
    'elbow_flexion',
    array['biceps']::text[],
    array['forearms']::text[],
    array['ez bar preacher curl']::text[],
    'total_external',
    null,
    null
  ),
  (
    'cable_curl',
    'Cable Curl',
    'upper',
    array['cable']::text[],
    null,
    'kg',
    false,
    'active',
    'cable',
    array['cable']::text[],
    'elbow_flexion',
    array['biceps']::text[],
    array['forearms']::text[],
    array[]::text[],
    'device_display',
    null,
    'dumbbell_curl'
  ),
  (
    'machine_preacher_curl',
    'Machine Preacher Curl',
    'upper',
    array['machine']::text[],
    null,
    'kg',
    false,
    'active',
    'machine',
    array['machine']::text[],
    'elbow_flexion',
    array['biceps']::text[],
    array['forearms']::text[],
    array[]::text[],
    'device_display',
    null,
    'ez_bar_preacher_curl'
  ),
  (
    'weighted_sit_up',
    'Weighted Sit-Up',
    'core',
    array['dumbbells']::text[],
    null,
    'kg',
    false,
    'active',
    'dumbbell',
    array['dumbbells']::text[],
    'trunk_flexion',
    array['core']::text[],
    array[]::text[],
    array[]::text[],
    'implement_weight',
    null,
    null
  ),
  (
    'reverse_crunch',
    'Reverse Crunch',
    'core',
    array['bodyweight']::text[],
    null,
    'kg',
    false,
    'active',
    'bodyweight',
    array['bodyweight']::text[],
    'trunk_flexion',
    array['core']::text[],
    array[]::text[],
    array[]::text[],
    'bodyweight_only',
    null,
    null
  ),
  (
    'side_lying_hip_abduction',
    'Side-Lying Hip Abduction',
    'lower',
    array['bodyweight']::text[],
    null,
    'kg',
    false,
    'active',
    'bodyweight',
    array['bodyweight']::text[],
    'hip_abduction',
    array['hip_abductors', 'glutes']::text[],
    array[]::text[],
    array[]::text[],
    'bodyweight_only',
    null,
    null
  ),
  (
    'hip_abduction_machine',
    'Hip Abduction Machine',
    'lower',
    array['machine']::text[],
    null,
    'kg',
    false,
    'active',
    'machine',
    array['machine']::text[],
    'hip_abduction',
    array['hip_abductors', 'glutes']::text[],
    array[]::text[],
    array[]::text[],
    'device_display',
    null,
    'side_lying_hip_abduction'
  ),
  (
    'smith_machine_squat',
    'Smith Machine Squat',
    'lower',
    array['smith_machine', 'plates']::text[],
    'squat',
    'kg',
    false,
    'active',
    'machine',
    array['smith_machine', 'plates']::text[],
    'squat',
    array['quads', 'glutes']::text[],
    array['hamstrings', 'core']::text[],
    array[]::text[],
    'device_display',
    null,
    'goblet_squat'
  ),
  (
    'single_leg_glute_bridge',
    'Single-Leg Glute Bridge',
    'posterior_chain',
    array['bodyweight']::text[],
    null,
    'kg',
    false,
    'active',
    'bodyweight',
    array['bodyweight']::text[],
    'hip_extension',
    array['glutes']::text[],
    array['hamstrings', 'core']::text[],
    array[]::text[],
    'bodyweight_only',
    null,
    null
  ),
  (
    'cable_glute_kickback',
    'Cable Glute Kickback',
    'posterior_chain',
    array['cable']::text[],
    null,
    'kg',
    false,
    'active',
    'cable',
    array['cable']::text[],
    'hip_extension',
    array['glutes']::text[],
    array['hamstrings', 'core']::text[],
    array[]::text[],
    'device_display',
    null,
    'single_leg_glute_bridge'
  ),
  (
    'side_lying_hip_adduction',
    'Side-Lying Hip Adduction',
    'lower',
    array['bodyweight']::text[],
    null,
    'kg',
    false,
    'active',
    'bodyweight',
    array['bodyweight']::text[],
    'hip_adduction',
    array['hip_adductors']::text[],
    array[]::text[],
    array[]::text[],
    'bodyweight_only',
    null,
    null
  ),
  (
    'hip_adduction_machine',
    'Hip Adduction Machine',
    'lower',
    array['machine']::text[],
    null,
    'kg',
    false,
    'active',
    'machine',
    array['machine']::text[],
    'hip_adduction',
    array['hip_adductors']::text[],
    array[]::text[],
    array[]::text[],
    'device_display',
    null,
    'side_lying_hip_adduction'
  ),
  (
    'dumbbell_floor_press',
    'Dumbbell Floor Press',
    'upper',
    array['dumbbells']::text[],
    'bench_press',
    'kg',
    false,
    'active',
    'dumbbell',
    array['dumbbells']::text[],
    'horizontal_push',
    array['chest']::text[],
    array['triceps', 'shoulders']::text[],
    array[]::text[],
    'implement_weight',
    null,
    null
  ),
  (
    'neutral_grip_dumbbell_bench_press',
    'Neutral-Grip Dumbbell Bench Press',
    'upper',
    array['dumbbells', 'bench']::text[],
    'bench_press',
    'kg',
    false,
    'active',
    'dumbbell',
    array['dumbbells', 'bench']::text[],
    'horizontal_push',
    array['chest']::text[],
    array['triceps', 'shoulders']::text[],
    array[]::text[],
    'implement_weight',
    null,
    null
  ),
  (
    'cable_fly',
    'Cable Fly',
    'upper',
    array['cable']::text[],
    'bench_press',
    'kg',
    false,
    'active',
    'cable',
    array['cable']::text[],
    'horizontal_push',
    array['chest']::text[],
    array['triceps', 'shoulders']::text[],
    array[]::text[],
    'device_display',
    null,
    'dumbbell_fly'
  ),
  (
    'incline_machine_chest_press',
    'Incline Machine Chest Press',
    'upper',
    array['machine']::text[],
    'bench_press',
    'kg',
    false,
    'active',
    'machine',
    array['machine']::text[],
    'horizontal_push',
    array['chest']::text[],
    array['triceps', 'shoulders']::text[],
    array[]::text[],
    'device_display',
    null,
    'incline_dumbbell_press'
  ),
  (
    'machine_shoulder_press',
    'Machine Shoulder Press',
    'upper',
    array['machine']::text[],
    'overhead_press',
    'kg',
    false,
    'active',
    'machine',
    array['machine']::text[],
    'vertical_push',
    array['shoulders']::text[],
    array['triceps', 'core']::text[],
    array[]::text[],
    'device_display',
    null,
    'standing_dumbbell_press'
  ),
  (
    'machine_lateral_raise',
    'Machine Lateral Raise',
    'upper',
    array['machine']::text[],
    null,
    'kg',
    false,
    'active',
    'machine',
    array['machine']::text[],
    'shoulder_abduction',
    array['shoulders']::text[],
    array['upper_back']::text[],
    array[]::text[],
    'device_display',
    null,
    'dumbbell_lateral_raise'
  ),
  (
    'assisted_dip',
    'Assisted Dip',
    'upper',
    array['machine', 'dip_bars']::text[],
    'bench_press',
    'kg',
    false,
    'active',
    'machine',
    array['machine', 'dip_bars']::text[],
    'horizontal_push',
    array['chest']::text[],
    array['triceps', 'shoulders']::text[],
    array[]::text[],
    'assistance',
    null,
    'dip'
  ),
  (
    'assisted_pull_up',
    'Assisted Pull-Up',
    'upper_back',
    array['machine', 'pull_up_bar']::text[],
    null,
    'kg',
    false,
    'active',
    'machine',
    array['machine', 'pull_up_bar']::text[],
    'vertical_pull',
    array['upper_back']::text[],
    array['biceps', 'core']::text[],
    array[]::text[],
    'assistance',
    null,
    'pull_up'
  ),
  (
    'single_arm_lat_pulldown',
    'Single-Arm Lat Pulldown',
    'upper_back',
    array['cable']::text[],
    null,
    'kg',
    false,
    'active',
    'cable',
    array['cable']::text[],
    'vertical_pull',
    array['upper_back']::text[],
    array['biceps', 'core']::text[],
    array[]::text[],
    'device_display',
    null,
    'pull_up'
  ),
  (
    'machine_pullover',
    'Machine Pullover',
    'upper_back',
    array['machine']::text[],
    null,
    'kg',
    false,
    'active',
    'machine',
    array['machine']::text[],
    'vertical_pull',
    array['upper_back']::text[],
    array['biceps', 'core']::text[],
    array[]::text[],
    'device_display',
    null,
    'dumbbell_pullover'
  ),
  (
    'dumbbell_shrug',
    'Dumbbell Shrug',
    'upper_back',
    array['dumbbells']::text[],
    null,
    'kg',
    false,
    'active',
    'dumbbell',
    array['dumbbells']::text[],
    'scapular_elevation',
    array['upper_back']::text[],
    array['forearms']::text[],
    array[]::text[],
    'implement_weight',
    null,
    null
  ),
  (
    'concentration_curl',
    'Concentration Curl',
    'upper',
    array['dumbbells']::text[],
    null,
    'kg',
    false,
    'active',
    'dumbbell',
    array['dumbbells']::text[],
    'elbow_flexion',
    array['biceps']::text[],
    array['forearms']::text[],
    array[]::text[],
    'implement_weight',
    null,
    null
  ),
  (
    'reverse_barbell_curl',
    'Reverse Barbell Curl',
    'upper',
    array['barbell', 'plates']::text[],
    null,
    'kg',
    false,
    'active',
    'barbell',
    array['barbell', 'plates']::text[],
    'elbow_flexion',
    array['biceps']::text[],
    array['forearms']::text[],
    array[]::text[],
    'total_external',
    null,
    null
  ),
  (
    'rope_hammer_curl',
    'Rope Hammer Curl',
    'upper',
    array['cable']::text[],
    null,
    'kg',
    false,
    'active',
    'cable',
    array['cable']::text[],
    'elbow_flexion',
    array['biceps']::text[],
    array['forearms']::text[],
    array[]::text[],
    'device_display',
    null,
    'hammer_curl'
  ),
  (
    'dumbbell_triceps_kickback',
    'Dumbbell Triceps Kickback',
    'upper',
    array['dumbbells']::text[],
    null,
    'kg',
    false,
    'active',
    'dumbbell',
    array['dumbbells']::text[],
    'elbow_extension',
    array['triceps']::text[],
    array['shoulders']::text[],
    array[]::text[],
    'implement_weight',
    null,
    null
  ),
  (
    'hanging_knee_raise',
    'Hanging Knee Raise',
    'core',
    array['bodyweight', 'pull_up_bar']::text[],
    null,
    'kg',
    false,
    'active',
    'bodyweight',
    array['bodyweight', 'pull_up_bar']::text[],
    'trunk_flexion',
    array['core']::text[],
    array[]::text[],
    array[]::text[],
    'bodyweight_only',
    null,
    null
  ),
  (
    'dumbbell_russian_twist',
    'Dumbbell Russian Twist',
    'core',
    array['dumbbells']::text[],
    null,
    'kg',
    false,
    'active',
    'dumbbell',
    array['dumbbells']::text[],
    'trunk_rotation',
    array['core']::text[],
    array[]::text[],
    array[]::text[],
    'implement_weight',
    null,
    null
  )
on conflict (id) do update set
  name = excluded.name,
  category = excluded.category,
  equipment = excluded.equipment,
  variation_of = excluded.variation_of,
  default_unit = excluded.default_unit,
  is_competition = excluded.is_competition,
  status = excluded.status,
  resistance_mode = excluded.resistance_mode,
  required_equipment = excluded.required_equipment,
  pattern = excluded.pattern,
  primary_muscles = excluded.primary_muscles,
  secondary_muscles = excluded.secondary_muscles,
  aliases = excluded.aliases,
  load_convention = excluded.load_convention,
  replaced_by_movement_id = excluded.replaced_by_movement_id,
  canonical_free_weight_movement_id =
    excluded.canonical_free_weight_movement_id;

insert into public.equipment_mode_policy_versions (
  id,
  mode,
  version,
  schema_version,
  definition
) values (
  '00000000-0000-4000-8000-000000000201',
  'free_weight',
  '1',
  '1',
  '{"rules":[{"id":"free-weight-v1-seated_cable_row","sourceMovementId":"seated_cable_row","replacementMovementIds":["barbell_row","landmine_t_bar_row","pendlay_row"],"loadHandling":"clear"},{"id":"free-weight-v1-machine_row","sourceMovementId":"machine_row","replacementMovementIds":["chest_supported_dumbbell_row","barbell_row","landmine_t_bar_row"],"loadHandling":"clear"},{"id":"free-weight-v1-one_arm_cable_row","sourceMovementId":"one_arm_cable_row","replacementMovementIds":["dumbbell_row","barbell_row","landmine_t_bar_row"],"loadHandling":"clear"},{"id":"free-weight-v1-chest_supported_row","sourceMovementId":"chest_supported_row","replacementMovementIds":["chest_supported_dumbbell_row","barbell_row","landmine_t_bar_row"],"loadHandling":"clear"},{"id":"free-weight-v1-lat_pulldown","sourceMovementId":"lat_pulldown","replacementMovementIds":["pull_up","dumbbell_pullover","chin_up"],"loadHandling":"clear"},{"id":"free-weight-v1-machine_high_row","sourceMovementId":"machine_high_row","replacementMovementIds":["chest_supported_dumbbell_row","barbell_row","landmine_t_bar_row"],"loadHandling":"clear"},{"id":"free-weight-v1-leg_press","sourceMovementId":"leg_press","replacementMovementIds":["goblet_squat","front_squat","high_box_squat"],"loadHandling":"clear"},{"id":"free-weight-v1-hack_squat","sourceMovementId":"hack_squat","replacementMovementIds":["goblet_squat","front_squat","high_box_squat"],"loadHandling":"clear"},{"id":"free-weight-v1-split_squat","sourceMovementId":"split_squat","replacementMovementIds":["dumbbell_split_squat","dumbbell_bulgarian_split_squat","dumbbell_lunge"],"loadHandling":"clear"},{"id":"free-weight-v1-hamstring_curl","sourceMovementId":"hamstring_curl","replacementMovementIds":["sliding_leg_curl","glute_ham_raise","nordic_hamstring_curl"],"loadHandling":"clear"},{"id":"free-weight-v1-seated_leg_curl","sourceMovementId":"seated_leg_curl","replacementMovementIds":["sliding_leg_curl","glute_ham_raise","nordic_hamstring_curl"],"loadHandling":"clear"},{"id":"free-weight-v1-lying_leg_curl","sourceMovementId":"lying_leg_curl","replacementMovementIds":["sliding_leg_curl","glute_ham_raise","nordic_hamstring_curl"],"loadHandling":"clear"},{"id":"free-weight-v1-back_extension","sourceMovementId":"back_extension","replacementMovementIds":["back_extension_45_degree","barbell_hip_thrust","single_leg_glute_bridge"],"loadHandling":"clear"},{"id":"free-weight-v1-reverse_hyperextension","sourceMovementId":"reverse_hyperextension","replacementMovementIds":["back_extension_45_degree","barbell_hip_thrust","single_leg_glute_bridge"],"loadHandling":"clear"},{"id":"free-weight-v1-cable_crunch","sourceMovementId":"cable_crunch","replacementMovementIds":["weighted_sit_up","ab_wheel_rollout","hanging_knee_raise"],"loadHandling":"clear"},{"id":"free-weight-v1-triceps_pressdown","sourceMovementId":"triceps_pressdown","replacementMovementIds":["dumbbell_triceps_kickback","barbell_french_press","barbell_skullcrusher"],"loadHandling":"clear"},{"id":"free-weight-v1-overhead_triceps_extension","sourceMovementId":"overhead_triceps_extension","replacementMovementIds":["dumbbell_overhead_triceps_extension","barbell_french_press","barbell_skullcrusher"],"loadHandling":"clear"},{"id":"free-weight-v1-skullcrusher","sourceMovementId":"skullcrusher","replacementMovementIds":["barbell_skullcrusher","barbell_french_press","jm_press"],"loadHandling":"clear"},{"id":"free-weight-v1-face_pull","sourceMovementId":"face_pull","replacementMovementIds":["dumbbell_rear_delt_fly","barbell_upright_row","dumbbell_lateral_raise"],"loadHandling":"clear"},{"id":"free-weight-v1-rear_delt_fly","sourceMovementId":"rear_delt_fly","replacementMovementIds":["dumbbell_rear_delt_fly","barbell_upright_row","dumbbell_lateral_raise"],"loadHandling":"clear"},{"id":"free-weight-v1-lunge","sourceMovementId":"lunge","replacementMovementIds":["dumbbell_lunge","dumbbell_bulgarian_split_squat","dumbbell_split_squat"],"loadHandling":"clear"},{"id":"free-weight-v1-t_bar_row","sourceMovementId":"t_bar_row","replacementMovementIds":["landmine_t_bar_row","barbell_row","pendlay_row"],"loadHandling":"clear"},{"id":"free-weight-v1-v_handle_pulldown","sourceMovementId":"v_handle_pulldown","replacementMovementIds":["neutral_grip_pull_up","dumbbell_pullover","chin_up"],"loadHandling":"clear"},{"id":"free-weight-v1-upright_row","sourceMovementId":"upright_row","replacementMovementIds":["barbell_upright_row","dumbbell_lateral_raise","dumbbell_rear_delt_fly"],"loadHandling":"clear"},{"id":"free-weight-v1-rope_pressdown","sourceMovementId":"rope_pressdown","replacementMovementIds":["dumbbell_triceps_kickback","barbell_french_press","barbell_skullcrusher"],"loadHandling":"clear"},{"id":"free-weight-v1-french_press","sourceMovementId":"french_press","replacementMovementIds":["barbell_french_press","barbell_skullcrusher","jm_press"],"loadHandling":"clear"},{"id":"free-weight-v1-side_bend","sourceMovementId":"side_bend","replacementMovementIds":["dumbbell_side_bend"],"loadHandling":"clear"},{"id":"free-weight-v1-machine_chest_supported_row","sourceMovementId":"machine_chest_supported_row","replacementMovementIds":["chest_supported_dumbbell_row","barbell_row","landmine_t_bar_row"],"loadHandling":"clear"},{"id":"free-weight-v1-machine_t_bar_row","sourceMovementId":"machine_t_bar_row","replacementMovementIds":["landmine_t_bar_row","barbell_row","pendlay_row"],"loadHandling":"clear"},{"id":"free-weight-v1-machine_back_extension","sourceMovementId":"machine_back_extension","replacementMovementIds":["barbell_hip_thrust","back_extension_45_degree","single_leg_glute_bridge"],"loadHandling":"clear"},{"id":"free-weight-v1-cable_overhead_triceps_extension","sourceMovementId":"cable_overhead_triceps_extension","replacementMovementIds":["dumbbell_overhead_triceps_extension","barbell_french_press","barbell_skullcrusher"],"loadHandling":"clear"},{"id":"free-weight-v1-reverse_pec_deck","sourceMovementId":"reverse_pec_deck","replacementMovementIds":["dumbbell_rear_delt_fly","barbell_upright_row","dumbbell_lateral_raise"],"loadHandling":"clear"},{"id":"free-weight-v1-cable_upright_row","sourceMovementId":"cable_upright_row","replacementMovementIds":["barbell_upright_row","dumbbell_lateral_raise","dumbbell_rear_delt_fly"],"loadHandling":"clear"},{"id":"free-weight-v1-cable_side_bend","sourceMovementId":"cable_side_bend","replacementMovementIds":["dumbbell_side_bend"],"loadHandling":"clear"},{"id":"free-weight-v1-leg_extension","sourceMovementId":"leg_extension","replacementMovementIds":["goblet_squat"],"loadHandling":"clear"},{"id":"free-weight-v1-standing_machine_calf_raise","sourceMovementId":"standing_machine_calf_raise","replacementMovementIds":["standing_dumbbell_calf_raise","seated_dumbbell_calf_raise"],"loadHandling":"clear"},{"id":"free-weight-v1-seated_machine_calf_raise","sourceMovementId":"seated_machine_calf_raise","replacementMovementIds":["seated_dumbbell_calf_raise","standing_dumbbell_calf_raise"],"loadHandling":"clear"},{"id":"free-weight-v1-hip_thrust_machine","sourceMovementId":"hip_thrust_machine","replacementMovementIds":["barbell_hip_thrust","back_extension_45_degree","single_leg_glute_bridge"],"loadHandling":"clear"},{"id":"free-weight-v1-machine_chest_press","sourceMovementId":"machine_chest_press","replacementMovementIds":["dumbbell_bench_press","bench_press","board_press"],"loadHandling":"clear"},{"id":"free-weight-v1-pec_deck","sourceMovementId":"pec_deck","replacementMovementIds":["dumbbell_fly","bench_press","board_press"],"loadHandling":"clear"},{"id":"free-weight-v1-cable_lateral_raise","sourceMovementId":"cable_lateral_raise","replacementMovementIds":["dumbbell_lateral_raise","barbell_upright_row","dumbbell_rear_delt_fly"],"loadHandling":"clear"},{"id":"free-weight-v1-straight_arm_cable_pulldown","sourceMovementId":"straight_arm_cable_pulldown","replacementMovementIds":["dumbbell_pullover","chin_up","neutral_grip_pull_up"],"loadHandling":"clear"},{"id":"free-weight-v1-cable_curl","sourceMovementId":"cable_curl","replacementMovementIds":["dumbbell_curl","barbell_curl","reverse_barbell_curl"],"loadHandling":"clear"},{"id":"free-weight-v1-machine_preacher_curl","sourceMovementId":"machine_preacher_curl","replacementMovementIds":["ez_bar_preacher_curl","barbell_curl","reverse_barbell_curl"],"loadHandling":"clear"},{"id":"free-weight-v1-hip_abduction_machine","sourceMovementId":"hip_abduction_machine","replacementMovementIds":["side_lying_hip_abduction"],"loadHandling":"clear"},{"id":"free-weight-v1-smith_machine_squat","sourceMovementId":"smith_machine_squat","replacementMovementIds":["goblet_squat","front_squat","high_box_squat"],"loadHandling":"clear"},{"id":"free-weight-v1-cable_glute_kickback","sourceMovementId":"cable_glute_kickback","replacementMovementIds":["single_leg_glute_bridge","barbell_hip_thrust","back_extension_45_degree"],"loadHandling":"clear"},{"id":"free-weight-v1-hip_adduction_machine","sourceMovementId":"hip_adduction_machine","replacementMovementIds":["side_lying_hip_adduction"],"loadHandling":"clear"},{"id":"free-weight-v1-cable_fly","sourceMovementId":"cable_fly","replacementMovementIds":["dumbbell_fly","bench_press","board_press"],"loadHandling":"clear"},{"id":"free-weight-v1-incline_machine_chest_press","sourceMovementId":"incline_machine_chest_press","replacementMovementIds":["incline_dumbbell_press","bench_press","board_press"],"loadHandling":"clear"},{"id":"free-weight-v1-machine_shoulder_press","sourceMovementId":"machine_shoulder_press","replacementMovementIds":["standing_dumbbell_press","behind_neck_press","overhead_press"],"loadHandling":"clear"},{"id":"free-weight-v1-machine_lateral_raise","sourceMovementId":"machine_lateral_raise","replacementMovementIds":["dumbbell_lateral_raise","barbell_upright_row","dumbbell_rear_delt_fly"],"loadHandling":"clear"},{"id":"free-weight-v1-assisted_dip","sourceMovementId":"assisted_dip","replacementMovementIds":["dip","bench_press","board_press"],"loadHandling":"clear"},{"id":"free-weight-v1-assisted_pull_up","sourceMovementId":"assisted_pull_up","replacementMovementIds":["pull_up","dumbbell_pullover","chin_up"],"loadHandling":"clear"},{"id":"free-weight-v1-single_arm_lat_pulldown","sourceMovementId":"single_arm_lat_pulldown","replacementMovementIds":["pull_up","dumbbell_pullover","chin_up"],"loadHandling":"clear"},{"id":"free-weight-v1-machine_pullover","sourceMovementId":"machine_pullover","replacementMovementIds":["dumbbell_pullover","chin_up","neutral_grip_pull_up"],"loadHandling":"clear"},{"id":"free-weight-v1-rope_hammer_curl","sourceMovementId":"rope_hammer_curl","replacementMovementIds":["hammer_curl","barbell_curl","reverse_barbell_curl"],"loadHandling":"clear"}]}'::jsonb
);

do $$
begin
  if (select count(*) from public.movements) < 151
    or (select count(*) from public.movements where status = 'active') < 140
    or (select count(*) from public.movements where status = 'deprecated') <> 11
    or exists (
      select 1
      from public.movements
      where status = 'active'
        and resistance_mode is null
    ) then
    raise exception 'MOVEMENT_CATALOG_INCOMPLETE';
  end if;
end;
$$;
