-- Keep the exercise row and its prescription snapshot in sync when an
-- accessory movement is substituted. The previous comparable is generated by
-- the trusted server from completed history; it is deliberately excluded from
-- the stable intent hash so exact receipt replay remains idempotent.

revoke all on function public.substitute_session_movement_v2(
  uuid, text, integer, jsonb, uuid, text, text, text, text, text
) from public, anon, authenticated;

drop function public.substitute_session_movement_v2(
  uuid, text, integer, jsonb, uuid, text, text, text, text, text
);

create function public.substitute_session_movement_v2(
  p_session_id uuid,
  p_request_id text,
  p_expected_state_version integer,
  p_intent jsonb,
  p_exercise_log_id uuid,
  p_performed_movement_id text,
  p_reason text,
  p_note text,
  p_scope text,
  p_phase_key text,
  p_previous jsonb default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_payload_hash text;
  v_replay_version integer;
  v_session public.workout_sessions%rowtype;
  v_exercise public.exercise_logs%rowtype;
  v_performed_movement_name text;
  v_snapshot jsonb;
  v_snapshot_movements jsonb;
  v_snapshot_match_count integer;
begin
  if p_intent is null
    or jsonb_typeof(p_intent) <> 'object'
    or octet_length(p_intent::text) > 50000
    or nullif(p_intent->>'exerciseLogId', '') is null
    or (p_intent->>'exerciseLogId')::uuid <> p_exercise_log_id
    or p_intent->>'performedMovementId' is distinct from p_performed_movement_id
    or p_intent->>'reason' is distinct from p_reason
    or p_intent->>'scope' is distinct from p_scope
    or (p_intent->>'note') is distinct from p_note
    or nullif(trim(p_performed_movement_id), '') is null
    or char_length(p_performed_movement_id) > 200
    or p_reason not in ('equipment_missing', 'crowded_gym', 'preference', 'fatigue', 'other')
    or char_length(coalesce(p_note, '')) > 2000
    or p_scope not in ('session', 'phase_slot') then
    raise exception 'VALIDATION_FAILED' using errcode = '22023';
  end if;

  v_payload_hash := md5(p_intent::text);
  v_replay_version := public.claim_session_mutation_v2(
    p_session_id,
    p_request_id,
    'substitute_session_movement',
    v_payload_hash,
    p_expected_state_version
  );
  if v_replay_version is not null then
    return jsonb_build_object('sessionId', p_session_id, 'stateVersion', v_replay_version);
  end if;

  -- Phase and comparable values are derived mutation data, so validate them
  -- only after accepting an exact stable-intent replay.
  if nullif(trim(p_phase_key), '') is null
    or char_length(p_phase_key) > 200
    or (
      p_previous is not null
      and (
        jsonb_typeof(p_previous) <> 'object'
        or octet_length(p_previous::text) > 50000
        or nullif(p_previous->>'movementId', '') is null
        or p_previous->>'movementId' is distinct from p_performed_movement_id
      )
    ) then
    raise exception 'VALIDATION_FAILED' using errcode = '22023';
  end if;

  select *
  into v_session
  from public.workout_sessions
  where id = p_session_id
    and user_id = v_user_id
  for update;
  if not found then
    raise exception 'SESSION_NOT_FOUND' using errcode = 'P0001';
  end if;

  select *
  into v_exercise
  from public.exercise_logs
  where id = p_exercise_log_id
    and session_id = p_session_id
    and user_id = v_user_id
  for update;
  if not found then
    raise exception 'EXERCISE_NOT_FOUND' using errcode = 'P0001';
  end if;
  if v_exercise.role = 'main' then
    raise exception 'MOVEMENT_SWAP_NOT_ALLOWED' using errcode = 'P0001';
  end if;

  select name
  into v_performed_movement_name
  from public.movements
  where id = p_performed_movement_id;
  if not found then
    raise exception 'MOVEMENT_INVALID' using errcode = 'P0001';
  end if;
  if p_scope = 'phase_slot' and v_session.program_instance_id is null then
    raise exception 'SESSION_KIND_MISMATCH' using errcode = 'P0001';
  end if;

  v_snapshot := v_session.prescription_snapshot;
  select count(*)
  into v_snapshot_match_count
  from jsonb_array_elements(v_snapshot->'movements') as snapshot_movement(movement)
  where coalesce(nullif(movement->>'slotId', ''), movement->>'id') = v_exercise.slot_id;
  if v_snapshot_match_count <> 1 then
    raise exception 'SNAPSHOT_STALE' using errcode = 'P0001';
  end if;

  select jsonb_agg(
    case
      when coalesce(nullif(movement->>'slotId', ''), movement->>'id') = v_exercise.slot_id
        then movement || jsonb_build_object(
          'performedMovementId', p_performed_movement_id,
          'performedMovementName', v_performed_movement_name,
          'previous', p_previous
        )
      else movement
    end
    order by movement_order
  )
  into v_snapshot_movements
  from jsonb_array_elements(v_snapshot->'movements')
    with ordinality as snapshot_movement(movement, movement_order);

  v_snapshot := jsonb_set(v_snapshot, '{movements}', v_snapshot_movements, false);
  perform public.validate_session_snapshot_v2(v_snapshot);

  update public.exercise_logs
  set performed_movement_id = p_performed_movement_id
  where id = p_exercise_log_id
    and session_id = p_session_id
    and user_id = v_user_id;

  insert into public.substitution_logs (
    user_id,
    session_id,
    slot_id,
    planned_movement_id,
    performed_movement_id,
    reason,
    note
  ) values (
    v_user_id,
    p_session_id,
    v_exercise.slot_id,
    v_exercise.planned_movement_id,
    p_performed_movement_id,
    p_reason,
    p_note
  );

  if p_scope = 'phase_slot' then
    perform public.session_set_program_movement_override(
      p_session_id,
      v_exercise.slot_id,
      p_phase_key,
      v_exercise.role,
      v_exercise.planned_movement_id,
      p_performed_movement_id,
      p_exercise_log_id,
      p_performed_movement_id = v_exercise.planned_movement_id
    );
  end if;

  return public.complete_session_mutation_v2(
    p_session_id,
    p_request_id,
    'substitute_session_movement',
    v_payload_hash,
    p_expected_state_version,
    v_snapshot
  );
end;
$$;

revoke all on function public.substitute_session_movement_v2(
  uuid, text, integer, jsonb, uuid, text, text, text, text, text, jsonb
) from public, anon;

grant execute on function public.substitute_session_movement_v2(
  uuid, text, integer, jsonb, uuid, text, text, text, text, text, jsonb
) to authenticated;
